apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  values:
    k8sServiceHost: '{{ .controlPlaneEndpointHost }}'
    k8sServicePort: '{{ .controlPlaneEndpointPort }}'
    ipam:
      operator:
        clusterPoolIPv4PodCIDRList:
          - '{{ .podsCidrBlocks }}'
