apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pdns-operator
spec:
  refreshInterval: '1h'
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: powerdns-operator-manager
    template:
      engineVersion: v2
      data:
        PDNS_API_URL: http://powerdns-api.powerdns.svc
        PDNS_API_KEY: '{{ .api_key }}'
        PDNS_API_VHOST: localhost
  data:
    - secretKey: api_key
      remoteRef:
        key: secrets/powerdns/server
        property: api_key
