apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-clusters
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: disk-hdd
  resources:
    requests:
      storage: 10Gi
