apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: kamaji-data
  namespace: velero
spec:
  schedule: 0 12 * * *
  template:
    includedNamespaces:
      - kamaji-system
    includedResources:
      - pvc
    snapshotMoveData: false
    ttl: 160h0m0s
    resourcePolicy:
      apiGroup: v1
      kind: ConfigMap
      name: velero-volume-policies
