apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: minio-clusters-data
  namespace: velero
spec:
  schedule: 0 12 * * *
  template:
    defaultVolumesToFsBackup: true
    includedNamespaces:
      - minio-clusters
    includedResources:
      - pvc
    snapshotMoveData: true
    ttl: 160h0m0s
