apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-setup
  namespace: flux-system
spec:
  interval: 30m
  path: ./gitops/apps/external-secret-operator/setup
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 30m
  path: ./gitops/apps/external-secret-operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra
  dependsOn:
    - name: external-secrets-setup
