apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-dns-secrets
  namespace: flux-system
spec:
  interval: 30m
  path: ./gitops/apps/external-dns/secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra
  dependsOn:
    - name: external-secrets
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-dns
  namespace: flux-system
spec:
  interval: 30m
  path: ./gitops/apps/external-dns
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra
