apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kamaji-console
  namespace: flux-system
spec:
  interval: 30m
  path: ./gitops/apps/kamaji-console
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra
