apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: minio-secrets
  namespace: flux-system
spec:
  interval: 1m
  path: ./gitops/apps/minio/secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra
  dependsOn:
    - name: external-secrets
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: minio
  namespace: flux-system
spec:
  interval: 1m
  path: ./gitops/apps/minio
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra
