apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: powerdns-operator-secrets
  namespace: flux-system
spec:
  interval: 1m
  path: ./gitops/apps/powerdns-operator/secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra
  dependsOn:
    - name: external-secrets
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: powerdns-operator
  namespace: flux-system
spec:
  interval: 1m
  path: ./gitops/apps/powerdns-operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra
