apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: proxmox-csi-secrets
  namespace: flux-system
spec:
  interval: 1m
  path: ./gitops/apps/proxmox-csi/secrets
  prune: false
  sourceRef:
    kind: GitRepository
    name: infra
  dependsOn:
    - name: external-secrets
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: proxmox-csi
  namespace: flux-system
spec:
  interval: 1m
  path: ./gitops/apps/proxmox-csi
  prune: false
  sourceRef:
    kind: GitRepository
    name: infra
