apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sveltos
  namespace: flux-system
spec:
  interval: 1m
  path: ./gitops/apps/sveltos
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sveltos-clusterprofiles
  namespace: flux-system
spec:
  interval: 1m
  path: ./gitops/apps/sveltos/clusterprofiles
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra
