apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: trust-manager
  namespace: flux-system
spec:
  interval: 1m
  path: ./gitops/apps/trust-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra
