apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vault-creds
spec:
  refreshInterval: '1h'
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: vault-creds
    template:
      engineVersion: v2
      data:
        credentials: |
          {
           "auth_login": {
             "path": "auth/approle/login",
             "parameters": {
               "role_id": "{{ .roleid }}",
               "secret_id": "{{ .secretid }}"
             }
           }
          }
  data:
    - secretKey: roleid
      remoteRef:
        key: secrets/vault/crossplane
        property: role-id
    - secretKey: secretid
      remoteRef:
        key: secrets/vault/crossplane
        property: secret-id
