apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: root-ca
  namespace: cert-manager
spec:
  refreshInterval: '1h'
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: root-ca
  data:
    - secretKey: ca.crt
      remoteRef:
        key: secrets/vault/pki_root_ca
        property: certificate
