apiVersion: v1
kind: ConfigMap
metadata:
  name: velero-volume-policies
  namespace: velero
data:
  policies.yaml: |
    version: v1
    volumePolicies:
    - conditions:
        volumeTypes:
          - emptyDir
          - downwardAPI
          - configmap
          - cinder
      action:
        type: skip
    - conditions:
        storageClass:
          - hdda
          - hddb
      action:
        type: skip
