apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 1h0m0s
  chart:
    spec:
      chart: velero
      version: 8.6.0
      sourceRef:
        kind: HelmRepository
        name: velero
  values:
    snapshotsEnabled: false
    deployNodeAgent: true
    nodeAgent:
      containerSecurityContext:
        privileged: true
    configuration:
      uploaderType: restic
      features: EnableCSI
      repositoryMaintenanceJob:
        requests:
          cpu: 100m
          memory: 1024Mi
        limits:
          cpu: 1
          memory: 1024Mi
      backupStorageLocation:
        - bucket: velero-mgmt
          name: default
          provider: aws
          prefix: fsb
          default: true
          config:
            region: minio
            s3ForcePathStyle: true
            s3Url: http://minio-mgmt.minio.svc:9000
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.8.1
        volumeMounts:
          - mountPath: /target
            name: plugins
    credentials:
      useSecret: true
      existingSecret: minio-credentials
