apiVersion: lib.projectsveltos.io/v1beta1
kind: EventSource
metadata:
  name: capsule-cluster-eventsource
spec:
  collectResources: true
  resourceSelectors:
    - group: ''
      version: 'v1'
      kind: 'Service'
      name: capsule-proxy-lb
      namespace: capsule-system
      evaluate: |
        function evaluate()
          hs = {}
          hs.matching = false
          hs.message = ""
          if obj.status.loadBalancer.ingress ~= nil then
            hs.matching = true
          end
          return hs
        end
---
apiVersion: lib.projectsveltos.io/v1beta1
kind: EventTrigger
metadata:
  name: capsule-bealv-eventtrigger
spec:
  sourceClusterSelector:
    matchLabels:
      capsule: 'true'
  destinationClusterSelector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: bealv
  eventSourceName: capsule-cluster-eventsource
  syncMode: Continuous
  reloader: true
  policyRefs:
    - kind: ConfigMap
      name: capsule-bealv-services
      namespace: projectsveltos
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: capsule-bealv-services
  namespace: projectsveltos
  annotations:
    projectsveltos.io/instantiate: 'true'
data:
  service.yaml: |
    apiVersion: v1
    kind: Service
    metadata:
      name: capsule-proxy-{{ .Cluster.metadata.name }}
      namespace: kube-system
    spec:
      internalTrafficPolicy: Cluster
      ipFamilies:
      - IPv4
      ipFamilyPolicy: SingleStack
      ports:
      - port: 8080
  endpointslice.yaml: |
    {{ $cluster := .Cluster }}
    {{- range $resource := .Resources }}
    addressType: IPv4
    apiVersion: discovery.k8s.io/v1
    kind: EndpointSlice
    metadata:
      labels:
        kubernetes.io/service-name: "capsule-proxy-{{ $cluster.metadata.name }}"
      name: "capsule-proxy-{{ $cluster.metadata.name }}"
      namespace: kube-system
    endpoints:
    - addresses:
      - {{ (index $resource.status.loadBalancer.ingress 0).ip }}
      conditions:
        ready: true
    ports:
    - name: ""
      port: 9001
      protocol: TCP
    {{ end }}
  ingress.yaml: |
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      annotations:
        cert-manager.io/cluster-issuer: bealvio
        external-dns.alpha.kubernetes.io/target: bealv.io
      name: "{{ .Cluster.metadata.name  }}"
      namespace: kube-system
    spec:
      ingressClassName: external
      rules:
      - host: "kube.{{ .Cluster.metadata.name }}.bealv.io"
        http:
          paths:
          - backend:
              service:
                name: "capsule-proxy-{{ .Cluster.metadata.name }}"
                port:
                  number: 8080
            path: /
            pathType: Prefix
      tls:
      - hosts:
        - "kube.{{ .Cluster.metadata.name }}.bealv.io"
        secretName: "kube.{{ .Cluster.metadata.name }}-tls"
