apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: capsule
spec:
  syncMode: ContinuousWithDriftDetection
  reloader: true
  clusterSelector:
    matchLabels:
      capsule: 'true'
  policyRefs:
    - kind: ConfigMap
      name: capsule-helm-resources
      namespace: projectsveltos
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: capsule-helm-resources
  namespace: projectsveltos
  annotations:
    projectsveltos.io/template: 'true'
data:
  helmrepository.yaml: |
    apiVersion: source.toolkit.fluxcd.io/v1
    kind: HelmRepository
    metadata:
      name: capsule
      namespace: flux-system
    spec:
      type: 'oci'
      interval: 12h0m0s
      url: oci://ghcr.io/projectcapsule/charts
  helmrelease.yaml: |-
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      name: capsule
      namespace: flux-system
    spec:
      serviceAccountName: kustomize-controller
      targetNamespace: 'capsule-system'
      interval: 10m
      releaseName: 'capsule'
      chart:
        spec:
          chart: capsule
          version: '0.10.9'
          sourceRef:
            kind: HelmRepository
            name: capsule
          interval: 24h
      install:
        createNamespace: true
      upgrade:
        remediation:
          remediateLastFailure: true
      driftDetection:
        mode: enabled
      values:
        crds:
          install: true
        certManager:
          generateCertificates: true
        tls:
          enableController: false
          create: false
        manager:
          options:
            capsuleConfiguration: default
            capsuleUserGroups:
              - "{{ .Cluster.metadata.name }}-kube-user"
              - kube-admin
            forceTenantPrefix: true
            ignoreUserWithGroups:
              - dummy
        webhooks:
          hooks:
            nodes:
              failurePolicy: Ignore
        serviceMonitor:
          enabled: false
        proxy:
          enabled: true
          image:
            registry: zot.bealv.io
            repository: public/capsule-proxy
            tag: latest
          webhooks:
            enabled: true
          certManager:
            generateCertificates: false
          options:
            SSLCertFileName: ''
            SSLKeyFileName: ''
            enableSSL: false
            generateCertificates: false
            oidcUsernameClaim: 'email'
            extraArgs:
              - '--feature-gates=ProxyClusterScoped=true'
              - '--feature-gates=ProxyAllNamespaced=true'
          resources:
            limits:
              memory: 256Mi
  tenant.yaml: |
    apiVersion: capsule.clastix.io/v1beta2
    kind: Tenant
    metadata:
      name: "{{ .Cluster.metadata.name }}-kube-user"
    spec:
      cordoned: false
      ingressOptions:
        hostnameCollisionScope: Disabled
      serviceOptions:
          allowedServices:
            nodePort: false
            loadBalancer: false
      resourceQuotas:
        items:
        - hard:
            limits.cpu: "4"
            limits.memory: 6Gi
            requests.cpu: "4"
            requests.memory: 6Gi
        - hard:
            requests.storage: 20Gi
      namespaceOptions:
        additionalMetadataList:
          - labels:
              pod-security.kubernetes.io/enforce: restricted
      owners:
      {{- $groups := splitList "," (index .Cluster.metadata.annotations "chihiro.io/groups") }}
      {{- range $groups }}
      {{- $group := trim . }}
      - clusterRoles:
        - admin
        - capsule-namespace-deleter
        kind: Group
        name: "{{ $group }}"
      {{- end }}
      - clusterRoles:
        - admin
        - capsule-namespace-deleter
        kind: Group
        name: "kube-admin"
      preventDeletion: false
      resourceQuotas:
        scope: Tenant
  globaltenantresource.yaml: |
    apiVersion: capsule.clastix.io/v1beta2
    kind: GlobalTenantResource
    metadata:
      name: netpol-lock
    spec:
      tenantSelector:
        matchLabels:
          kubernetes.io/metadata.name: "{{ .Cluster.metadata.name }}-kube-user"
      resyncPeriod: 60s
      resources:
        - namespaceSelector:
            matchLabels:
              capsule.clastix.io/tenant: "{{ .Cluster.metadata.name }}-kube-user"
          rawItems:
          - apiVersion: networking.k8s.io/v1
            kind: NetworkPolicy
            metadata:
              labels:
                capsule.clastix.io/tenant: "{{ .Cluster.metadata.name }}-kube-user"
              name: netpol-lock
            spec:
              ingress:
              - from:
                - namespaceSelector:
                    matchLabels:
                      capsule.clastix.io/tenant: oil
              policyTypes:
              - Ingress
          - apiVersion: networking.k8s.io/v1
            kind: NetworkPolicy
            metadata:
              name: allow-all-except-local
              namespace: default
            spec:
              podSelector: {} # Applies to all pods in the namespace
              policyTypes:
                - Ingress
                - Egress
              ingress:
                - from:
                    - ipBlock:
                        cidr: 0.0.0.0/0
                        except:
                          - 192.168.0.0/16
                          - 10.0.0.0/8
              egress:
                - to:
                    - ipBlock:
                        cidr: 0.0.0.0/0
                        except:
                          - 192.168.0.0/16
                          - 10.0.0.0/8
  namespace.yaml: |
    apiVersion: v1
    kind: Namespace
    metadata:
      labels:
        capsule.clastix.io/tenant: "{{ .Cluster.metadata.name }}-kube-user"
        kubernetes.io/metadata.name: "{{ .Cluster.metadata.name }}-kube-user-default"
        pod-security.kubernetes.io/enforce: restricted
      name: dev-kube-user-default
    spec:
  service.yaml: |
    apiVersion: v1
    kind: Service
    metadata:
      name: capsule-proxy-lb
      namespace: capsule-system
    spec:
      internalTrafficPolicy: Cluster
      ipFamilies:
      - IPv4
      ipFamilyPolicy: SingleStack
      ports:
      - name: proxy
        port: 9001
      selector:
        app.kubernetes.io/instance: capsule
        app.kubernetes.io/name: proxy
      type: LoadBalancer
