apiVersion: lib.projectsveltos.io/v1beta1
kind: EventSource
metadata:
  name: certvault-cluster-eventsource
spec:
  collectResources: true
  resourceSelectors:
    - kind: 'Deployment'
      version: 'v1'
      group: 'apps'
      name: 'cert-manager'
      namespace: 'cert-manager'
---
apiVersion: lib.projectsveltos.io/v1beta1
kind: EventTrigger
metadata:
  name: certvault-cluster-eventtrigger
spec:
  sourceClusterSelector:
    matchLabels:
      cert-manager: 'true'
  destinationClusterSelector:
    matchLabels:
      type: mgmt
  eventSourceName: certvault-cluster-eventsource
  syncMode: ContinuousWithDriftDetection
  reloader: true
  policyRefs:
    - kind: ConfigMap
      name: certvault-vault
      namespace: projectsveltos
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: certvault-vault
  annotations:
    projectsveltos.io/instantiate: 'true'
data:
  certmanager-roleid: |
    {{- $cluster := .Cluster }}
    ---
    apiVersion: approle.vault.upbound.io/v1alpha1
    kind: AuthBackendRole
    metadata:
      name: cert-manager-{{ $cluster.metadata.name }}
    spec:
      forProvider:
        roleName: cert-manager-{{ $cluster.metadata.name }}
        tokenPolicies:
          - cert-manager-{{ $cluster.metadata.name }}
      providerConfigRef:
        name: default
    ---
    apiVersion: approle.vault.upbound.io/v1alpha1
    kind: AuthBackendRoleSecretID
    metadata:
      name: cert-manager-{{ $cluster.metadata.name }}
    spec:
      forProvider:
        roleName: cert-manager-{{ $cluster.metadata.name }}
      writeConnectionSecretToRef:
        name: cert-manager-approle-{{ $cluster.metadata.name }}
        namespace: crossplane-system
      providerConfigRef:
        name: default
    ---
    apiVersion: vault.vault.upbound.io/v1alpha1
    kind: Policy
    metadata:
      name: cert-manager-{{ $cluster.metadata.name }}
    spec:
      forProvider:
        name: cert-manager-{{ $cluster.metadata.name }}
        policy: |
          path "pki-int/sign/{{ $cluster.metadata.name }}-dot-lan" {
            capabilities = ["create", "update"]
          }
          path "pki-int/issue/{{ $cluster.metadata.name }}-dot-lan" {
            capabilities = ["create", "update"]
          }
      providerConfigRef:
        name: default
    ---
    apiVersion: pki.vault.upbound.io/v1alpha1
    kind: SecretBackendRole
    metadata:
      name: {{ $cluster.metadata.name }}
    spec:
      forProvider:
        name: {{ $cluster.metadata.name }}-dot-lan
        backend: pki-int
        ttl: '2592000'
        allowIpSans: true
        keyType: rsa
        keyBits: 2048
        allowedDomains:
          - '{{ $cluster.metadata.name }}.lan'
        allowSubdomains: true
        organization:
          - 'Bealv'
        locality:
          - 'Bordeaux'
        province:
          - 'Gironde'
        country:
          - 'FR'
        postalCode:
          - '33000'
        requireCn: false
      providerConfigRef:
        name: default
    ---
    apiVersion: config.projectsveltos.io/v1beta1
    kind: ClusterProfile
    metadata:
      name: cert-manager-configs-{{ $cluster.metadata.name }}
    spec:
      syncMode: ContinuousWithDriftDetection
      reloader: true
      clusterSelector:
        matchLabels:
          cert-manager: 'true'
          cluster.x-k8s.io/cluster-name: {{ $cluster.metadata.name }}
      policyRefs:
        - kind: Secret
          name: cacert-clusterprofile
          namespace: projectsveltos
        - name: clusterissuer-clusterprofile
          namespace: projectsveltos
          kind: ConfigMap
      templateResourceRefs:
        - resource:
            apiVersion: v1
            kind: Secret
            name: bealv-mgmt-bundle
            namespace: cert-manager
          identifier: caSecrets
        - resource:
            apiVersion: approle.vault.upbound.io/v1alpha1
            kind: AuthBackendRole
            name: cert-manager-{{ $cluster.metadata.name }}
          identifier: AuthBackendRoleCert
        - resource:
            apiVersion: v1
            kind: Secret
            name: cert-manager-approle-{{ $cluster.metadata.name }}
            namespace: crossplane-system
          identifier: certManagerApproleSecretId
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: clusterissuer-clusterprofile
  annotations:
    projectsveltos.io/template: 'true'
data:
  clusterissuer.yaml: |
    apiVersion: cert-manager.io/v1
    kind: ClusterIssuer
    metadata:
      name: {{ .Cluster.metadata.name }}
    spec:
      vault:
        path: pki-int/sign/{{ .Cluster.metadata.name }}-dot-lan
        server: https://vault.bealv-mgmt.lan
        caBundleSecretRef:
          name: bealv-mgmt-bundle
          key: ca.crt
        auth:
          appRole:
            roleId: '{{ index (getResource "AuthBackendRoleCert").status.atProvider "roleId" }}'
            path: approle
            secretRef:
              name: cert-manager-approle-{{ .Cluster.metadata.name }}
              key: 'attribute.secret_id'
---
apiVersion: v1
kind: Secret
metadata:
  name: cacert-clusterprofile
  annotations:
    projectsveltos.io/template: 'true'
type: addons.projectsveltos.io/cluster-profile
stringData:
  secret.yaml: |
    apiVersion: v1
    kind: Secret
    metadata:
      name: root-ca
      namespace: {{ (getResource "caSecrets").metadata.namespace }}
    data:
      ca.crt: {{ index (getResource "caSecrets").data "ca.crt" }}
  token.yaml: |
    apiVersion: v1
    kind: Secret
    metadata:
      name: cert-manager-approle-{{ .Cluster.metadata.name }}
      namespace: cert-manager
    data:
      attribute.secret_id: '{{ index (getResource "certManagerApproleSecretId").data "attribute.secret_id" }}'
