apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: cert-manager
spec:
  syncMode: ContinousWithDriftDetection
  reloader: true
  clusterSelector:
    matchLabels:
      cert-manager: 'true'
  kustomizationRefs:
    - kind: GitRepository
      name: infra
      namespace: flux-system
      path: ./gitops/apps/cert-manager/upstream
---
apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: cert-manager-configs
spec:
  syncMode: ContinousWithDriftDetection
  reloader: true
  clusterSelector:
    matchLabels:
      cert-manager: 'true'
  policyRefs:
    - kind: Secret
      name: cacert-clusterprofile
      namespace: projectsveltos
    - name: clusterissuer-clusterprofile
      namespace: projectsveltos
      kind: ConfigMap
  templateResourceRefs:
    - resource:
        apiVersion: v1
        kind: Secret
        name: bealv-mgmt-bundle
        namespace: cert-manager
      identifier: caSecrets
    - resource:
        apiVersion: approle.vault.upbound.io/v1alpha1
        kind: AuthBackendRole
        name: cert-manager-{{ .Cluster.metadata.name }}
      identifier: AuthBackendRoleCert
    - resource:
        apiVersion: v1
        kind: Secret
        name: cert-manager-approle-{{ .Cluster.metadata.name }}
        namespace: crossplane-system
      identifier: certManagerApproleSecretId
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: clusterissuer-clusterprofile
  annotations:
    projectsveltos.io/template: 'true'
data:
  clusterissuer.yaml: |
    apiVersion: cert-manager.io/v1
    kind: ClusterIssuer
    metadata:
      name: {{ .Cluster.metadata.name }}
    spec:
      vault:
        path: pki-int/sign/{{ .Cluster.metadata.name }}-dot-lan
        server: https://vault.bealv-mgmt.lan
        caBundleSecretRef:
          name: bealv-mgmt-bundle
          key: ca.crt
        auth:
          appRole:
            roleId: '{{ index (getResource "AuthBackendRoleCert").status.atProvider "roleId" }}'
            path: approle
            secretRef:
              name: cert-manager-approle-{{ .Cluster.metadata.name }}
              key: 'attribute.secret_id'
---
apiVersion: v1
kind: Secret
metadata:
  name: cacert-clusterprofile
  annotations:
    projectsveltos.io/template: 'true'
type: addons.projectsveltos.io/cluster-profile
stringData:
  secret.yaml: |
    apiVersion: v1
    kind: Secret
    metadata:
      name: root-ca
      namespace: {{ (getResource "caSecrets").metadata.namespace }}
    data:
      ca.crt: {{ index (getResource "caSecrets").data "ca.crt" }}
  token.yaml: |
    apiVersion: v1
    kind: Secret
    metadata:
      name: cert-manager-approle-{{ .Cluster.metadata.name }}
      namespace: cert-manager
    data:
      attribute.secret_id: '{{ index (getResource "certManagerApproleSecretId").data "attribute.secret_id" }}'
