apiVersion: lib.projectsveltos.io/v1beta1
kind: EventSource
metadata:
  name: certvault-cluster-eventsource
spec:
  collectResources: true
  resourceSelectors:
    - group: 'config.projectsveltos.io'
      version: 'v1beta1'
      kind: 'ClusterProfile'
      labelFilters:
        - key: projectsveltos.io/cluster-profile-name
          value: 'cert-manager'
          operation: Equal
---
apiVersion: lib.projectsveltos.io/v1beta1
kind: EventTrigger
metadata:
  name: certvault-cluster-eventtrigger
spec:
  sourceClusterSelector:
    matchLabels:
      type: mgmt
  eventSourceName: certvault-cluster-eventsource
  syncMode: Continuous
  reloader: true
  policyRefs:
    - kind: ConfigMap
      name: certvault-vault
      namespace: projectsveltos
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: certvault-vault
  annotations:
    projectsveltos.io/instantiate: 'true'
data:
  certmanager-roleid: |
    apiVersion: approle.vault.upbound.io/v1alpha1
    kind: AuthBackendRole
    metadata:
      name: cert-manager-{{ index .Resource.metadata.labels "projectsveltos.io/cluster-name" }}
    spec:
      forProvider:
        roleName: cert-manager-{{ index .Resource.metadata.labels "projectsveltos.io/cluster-name" }}
        tokenPolicies:
          - cert-manager-{{ index .Resource.metadata.labels "projectsveltos.io/cluster-name" }}
      providerConfigRef:
        name: default
  certmanager-role-secretid: |
    apiVersion: approle.vault.upbound.io/v1alpha1
    kind: AuthBackendRoleSecretID
    metadata:
      name: cert-manager-{{ index .Resource.metadata.labels "projectsveltos.io/cluster-name" }}
    spec:
      forProvider:
        roleName: cert-manager-{{ index .Resource.metadata.labels "projectsveltos.io/cluster-name" }}
      writeConnectionSecretToRef:
        name: cert-manager-approle-{{ index .Resource.metadata.labels "projectsveltos.io/cluster-name" }}
        namespace: crossplane-system
      providerConfigRef:
        name: default
  policy.yaml: |
    apiVersion: vault.vault.upbound.io/v1alpha1
    kind: Policy
    metadata:
      name: cert-manager-{{ index .Resource.metadata.labels "projectsveltos.io/cluster-name" }}
    spec:
      forProvider:
        name: cert-manager-{{ index .Resource.metadata.labels "projectsveltos.io/cluster-name" }}
        policy: |
          path "pki-int/sign/{{ index .Resource.metadata.labels "projectsveltos.io/cluster-name" }}-dot-lan" {
            capabilities = ["create", "update"]
          }
          path "pki-int/issue/{{ index .Resource.metadata.labels "projectsveltos.io/cluster-name" }}-dot-lan" {
            capabilities = ["create", "update"]
          }
      providerConfigRef:
        name: default
  backend.yaml: |
    apiVersion: pki.vault.upbound.io/v1alpha1
    kind: SecretBackendRole
    metadata:
      name: {{ index .Resource.metadata.labels "projectsveltos.io/cluster-name" }}
    spec:
      forProvider:
        name: {{ index .Resource.metadata.labels "projectsveltos.io/cluster-name" }}-dot-lan
        backend: pki-int
        ttl: '2592000'
        allowIpSans: true
        keyType: rsa
        keyBits: 2048
        allowedDomains:
          - '{{ index .Resource.metadata.labels "projectsveltos.io/cluster-name" }}.lan'
        allowSubdomains: true
        organization:
          - 'Bealv'
        locality:
          - 'Bordeaux'
        province:
          - 'Gironde'
        country:
          - 'FR'
        postalCode:
          - '33000'
        requireCn: false
      providerConfigRef:
        name: default
