apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: cilium-bootstrap
  namespace: projectsveltos
spec:
  clusterSelector:
    matchLabels:
      cni: cilium
  policyRefs:
    - name: cilium-conf-clusterprofile
      namespace: projectsveltos
      kind: ConfigMap
  helmCharts:
    - repositoryURL: https://helm.cilium.io/
      repositoryName: cilium
      chartName: cilium/cilium
      chartVersion: 1.18.0-pre.2
      releaseName: cilium
      releaseNamespace: kube-system
      helmChartAction: Install
      values: |
        k8sServiceHost: "{{ .Cluster.spec.controlPlaneEndpoint.host }}"
        k8sServicePort: "{{ .Cluster.spec.controlPlaneEndpoint.port }}"
        operator:
          replicas: 1
          updateStrategy:
            type: Recreate
            rollingUpdate: null
        l2announcements:
          enabled: true
        socketLB:
          hostNamespaceOnly: true
        kubeProxyReplacement: true
        envoy:
          enabled: false
        cni:
          exclusive: false
        ipam:
          operator:
            clusterPoolIPv4PodCIDRList:
              - {{ index .Cluster.spec.clusterNetwork.pods.cidrBlocks 0 }}
            clusterPoolIPv4MaskSize: 23
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cilium-conf-clusterprofile
  annotations:
    projectsveltos.io/template: 'true'
data:
  cilium-conf.yaml: |
    apiVersion: 'cilium.io/v2alpha1'
    kind: CiliumL2AnnouncementPolicy
    metadata:
      name: default
    spec:
      externalIPs: false
      loadBalancerIPs: true
