apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: external-dns
spec:
  reloader: true
  syncMode: ContinuousWithDriftDetection
  clusterSelector:
    matchLabels:
      external-dns: 'true'
      cert-manager: 'true'
  kustomizationRefs:
    - kind: GitRepository
      name: infra
      namespace: flux-system
      path: ./gitops/apps/sveltos/clusterprofiles/templates/external-dns
      values:
        ClusterName: '{{ .Cluster.metadata.name }}'
  policyRefs:
    - kind: Secret
      name: dnsapi-clusterprofile
      namespace: projectsveltos
  templateResourceRefs:
    - resource:
        apiVersion: v1
        kind: Secret
        name: powerdns
        namespace: powerdns
      identifier: dnsSecrets
    - resource:
        apiVersion: v1
        kind: Secret
        name: root-ca
        namespace: cert-manager
      identifier: caSecrets
---
apiVersion: v1
kind: Secret
metadata:
  name: dnsapi-clusterprofile
  annotations:
    projectsveltos.io/template: 'true'
type: addons.projectsveltos.io/cluster-profile
stringData:
  secret.yaml: |
    apiVersion: v1
    kind: Secret
    metadata:
      name: external-dns-internal
      namespace: external-dns
    data:
      api_key: {{ index (getResource "dnsSecrets").data "api_key" }}
  ca.crt.yaml: |
    apiVersion: v1
    kind: Secret
    metadata:
      name: bealv-mgmt
      namespace: external-dns
    data:
      ca.crt: {{ index (getResource "caSecrets").data "ca.crt" }}
