apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: external-dns
spec:
  stopMatchingBehavior: LeavePolicies
  syncMode: ContinuousWithDriftDetection
  clusterSelector:
    matchLabels:
      type: workload
      addons.bealv.io/external-dns: "enabled"
    matchExpressions:
      # any cert-manager variant (gatewayapi or generic)
      - key: addons.bealv.io/cert-manager
        operator: Exists
  kustomizationRefs:
    - kind: GitRepository
      name: infra
      namespace: flux-system
      path: ./gitops/apps/sveltos/clusterprofiles/templates/external-dns
      values:
        ClusterName: "{{ .Cluster.metadata.name }}"
  policyRefs:
    - kind: Secret
      name: dnsapi-clusterprofile
      namespace: projectsveltos
  templateResourceRefs:
    - resource:
        apiVersion: v1
        kind: Secret
        name: powerdns
        namespace: powerdns
      identifier: dnsSecrets
---
apiVersion: v1
kind: Secret
metadata:
  name: dnsapi-clusterprofile
  annotations:
    projectsveltos.io/template: "true"
type: addons.projectsveltos.io/cluster-profile
stringData:
  secret.yaml: |
    apiVersion: v1
    kind: Secret
    metadata:
      name: external-dns-internal
      namespace: external-dns
    data:
      api_key: {{ index (getResource "dnsSecrets").data "api_key" }}
---
apiVersion: lib.projectsveltos.io/v1beta1
kind: EventSource
metadata:
  name: pdns-cluster-eventsource
spec:
  collectResources: true
  resourceSelectors:
    - group: "apps"
      version: "v1"
      kind: "Deployment"
      name: "external-dns-internal"
      namespace: "external-dns"
---
apiVersion: lib.projectsveltos.io/v1beta1
kind: EventTrigger
metadata:
  name: pdns-cluster-eventtrigger
spec:
  stopMatchingBehavior: LeavePolicies
  sourceClusterSelector:
    matchLabels:
      type: workload
      addons.bealv.io/external-dns: "enabled"
  destinationClusterSelector:
    matchLabels:
      type: "mgmt"
  eventSourceName: pdns-cluster-eventsource
  syncMode: ContinuousWithDriftDetection
  reloader: true
  oneForEvent: true
  policyRefs:
    - kind: ConfigMap
      name: pdns-zone
      namespace: projectsveltos
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pdns-zone
  annotations:
    projectsveltos.io/instantiate: "true"
data:
  zone.yaml: |
    apiVersion: dns.cav.enablers.ob/v1alpha1
    kind: Zone
    metadata:
      name: {{ .Cluster.metadata.name }}.lan
    spec:
      nameservers:
        - dummy.{{ .Cluster.metadata.name }}.lan
      kind: Native
---
