apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: ingress-controller
spec:
  syncMode: ContinuousWithDriftDetection
  reloader: true
  clusterSelector:
    matchLabels:
      ingress-controller: 'true'
  kustomizationRefs:
    - kind: GitRepository
      name: infra
      namespace: flux-system
      path: ./gitops/apps/ingress-controller
