apiVersion: lib.projectsveltos.io/v1beta1
kind: EventSource
metadata:
  name: ingress-eventsource
spec:
  collectResources: true
  resourceSelectors:
    - group: 'networking.k8s.io'
      version: 'v1'
      kind: 'Ingress'
---
apiVersion: lib.projectsveltos.io/v1beta1
kind: EventTrigger
metadata:
  name: ingress-to-httproute
spec:
  sourceClusterSelector:
    matchLabels:
      ingress-replication: 'true'
  destinationClusterSelector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: bealv
  eventSourceName: ingress-eventsource
  syncMode: ContinuousWithDriftDetection
  policyRefs:
    - kind: ConfigMap
      name: httproute-template
      namespace: projectsveltos
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: httproute-template
  namespace: projectsveltos
  annotations:
    projectsveltos.io/instantiate: 'true'
data:
  httproute.yaml: |
    {{ $cluster := .Cluster }}
    {{- range $resource := .Resources }}
    {{ range $rule := $resource.spec.rules }}
    {{ range $path := $rule.http.paths }}
    {{ $ingressHost := $rule.host }}
    {{/* Construct the old and new suffix strings using the $cluster variable */}}
    {{ $oldSuffix := printf "%s.lan" $cluster }}
    {{ $newSuffix := printf "%s.bealv.io" $cluster }}
    {{/* Use the variables in the replace function */}}
    {{ $routeHost := $ingressHost | replace $oldSuffix $newSuffix }}

    {{ $resourceId := printf "%s%s%s%s" $ingressHost $path.backend.service.name $resource.metadata.namespace $cluster.metadata.name | sha256sum | trunc 8 }}
    ---
    apiVersion: gateway.kgateway.dev/v1alpha1
    kind: Backend
    metadata:
      name: backend-{{ $resourceId }}
      namespace: kube-system
      labels:
        generated-by: sveltosingressreplication
        cluster: {{ $cluster.metadata.name }}
        service: {{ $path.backend.service.name }}
    spec:
      type: Static
      static:
        hosts:
          - host: {{ $ingressHost }}
            port: 443
    ---
    apiVersion: gateway.networking.k8s.io/v1
    kind: HTTPRoute
    metadata:
      name: httproute-{{ $resourceId }}
      namespace: kube-system
      labels:
        generated-by: sveltosingressreplication
        cluster: {{ $cluster.metadata.name }}
        service: {{ $path.backend.service.name }}
    spec:
      parentRefs:
        - name: https
          namespace: kgateway-system
      hostnames:
        - {{ $routeHost }}
      rules:
        - backendRefs:
            - group: gateway.kgateway.dev
              kind: Backend
              name: backend-{{ $resourceId }}
    {{ end }}
    {{ end }}
    {{ end }}
