apiVersion: lib.projectsveltos.io/v1beta1
kind: EventSource
metadata:
  name: ingress-eventsource
spec:
  collectResources: true
  resourceSelectors:
    - group: 'networking.k8s.io'
      version: 'v1'
      kind: 'Ingress'
---
apiVersion: lib.projectsveltos.io/v1beta1
kind: EventTrigger
metadata:
  name: ingress-to-httproute
spec:
  sourceClusterSelector:
    matchLabels:
      ingress-replication: 'true'
  destinationClusterSelector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: bealv
  eventSourceName: ingress-eventsource
  syncMode: ContinuousWithDriftDetection
  policyRefs:
    - kind: ConfigMap
      name: httproute-template
      namespace: projectsveltos
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: httproute-template
  namespace: projectsveltos
  annotations:
    projectsveltos.io/instantiate: 'true'
data:
  httproute.yaml: |
    {{ $cluster := .Cluster }}
    {{- range $resource := .Resources }}
    {{ range $rule := $resource.spec.rules }}
    {{ range $path := $rule.http.paths }}
    {{ $ingressHost := $rule.host }}
    {{ $routeHost := $ingressHost | replace ".lan" ".bealv.io" }}
    {{ $resourceId := printf "%s%s%s%s" $ingressHost $path.backend.service.name $resource.metadata.namespace $cluster.metadata.name | sha256sum | trunc 8 }}
    ---
    apiVersion: gateway.kgateway.dev/v1alpha1
    kind: Backend
    metadata:
      name: backend-{{ $resourceId }}
      namespace: sveltos-{{ $cluster.metadata.name }}
      labels:
        generated-by: sveltosingressreplication
        cluster: {{ $cluster.metadata.name }}
        service: {{ $path.backend.service.name }}
    spec:
      type: Static
      static:
        hosts:
          - host: {{ $ingressHost }}
            port: 443
    ---
    apiVersion: gateway.networking.k8s.io/v1
    kind: BackendTLSPolicy
    metadata:
      name: static-tls-policy-{{ $resourceId }}
      namespace: sveltos-{{ $cluster.metadata.name }}
    spec:
      targetRefs:
      - group: gateway.kgateway.dev
        kind: Backend
        name: backend-{{ $resourceId }}
      validation:
        hostname: "{{ $ingressHost }}"
        wellKnownCACertificates: System
        caCertificateRefs:
          - kind: Secret
            group: ""
            name: bealv-mgmt-bundle
    ---
    apiVersion: gateway.networking.k8s.io/v1
    kind: HTTPRoute
    metadata:
      name: httproute-{{ $resourceId }}
      namespace: sveltos-{{ $cluster.metadata.name }}
      labels:
        generated-by: sveltosingressreplication
        cluster: {{ $cluster.metadata.name }}
        service: {{ $path.backend.service.name }}
    spec:
      parentRefs:
        - name: {{ $cluster.metadata.name }}-ingress
          group: gateway.networking.x-k8s.io
          kind: XListenerSet
          namespace: sveltos-{{ $cluster.metadata.name }}
      hostnames:
        - {{ $routeHost }}
      rules:
        - backendRefs:
            - group: gateway.kgateway.dev
              kind: Backend
              name: backend-{{ $resourceId }}
          filters:
          - type: URLRewrite
            urlRewrite:
              hostname: {{ $ingressHost }}
    {{ end }}
    {{ end }}
    {{ end }}
