namespace: projectsveltos
resources:
  - cilium.yaml
  - fluxcd.yaml
  - proxmox-csi.yaml
  - cert-manager.yaml
  - trust-manager.yaml
  - external-dns.yaml
  - ingress-controller.yaml
  - external-secret.yaml
  - velero.yaml
  - external-snapshotter.yaml
  - monitoring.yaml
  - capsule.yaml
  - ingress-replication.yaml
  - ballast.yaml
  - descheduler.yaml
