apiVersion: cluster.x-k8s.io/v1beta1
kind: ClusterClass
metadata:
  name: kamaji-proxmox
  namespace: capi-system
spec:
  variables:
    - name: ipv4Config
      required: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            addresses:
              type: array
              items:
                type: string
            gateway:
              type: string
            prefix:
              type: integer
    - name: dnsServers
      required: true
      schema:
        openAPIV3Schema:
          type: array
          items:
            type: string
    - name: templateID
      required: true
      schema:
        openAPIV3Schema:
          type: integer
    - name: templateGPUID
      required: false
      schema:
        openAPIV3Schema:
          type: integer
  patches:
    - name: proxmox-cluster
      definitions:
        - selector:
            apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
            kind: ProxmoxClusterTemplate
            matchResources:
              infrastructureCluster: true
          jsonPatches:
            - op: replace
              path: /spec/template/spec/ipv4Config
              valueFrom:
                variable: ipv4Config
            - op: replace
              path: /spec/template/spec/dnsServers
              valueFrom:
                variable: dnsServers
    - name: templateID
      definitions:
        - selector:
            apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
            kind: ProxmoxMachineTemplate
            matchResources:
              machineDeploymentClass:
                names:
                  - default-worker
          jsonPatches:
            - op: replace
              path: /spec/template/spec/templateID
              valueFrom:
                variable: templateID
    - name: templateGPUID
      definitions:
        - selector:
            apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
            kind: ProxmoxMachineTemplate
            matchResources:
              machineDeploymentClass:
                names:
                  - default-worker-gpu
          jsonPatches:
            - op: replace
              path: /spec/template/spec/templateID
              valueFrom:
                variable: templateGPUID
  controlPlane:
    ref:
      apiVersion: controlplane.cluster.x-k8s.io/v1alpha1
      kind: KamajiControlPlaneTemplate
      name: kamaji-proxmox
      namespace: capi-system
  infrastructure:
    ref:
      apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
      kind: ProxmoxClusterTemplate
      name: kamaji-proxmox
      namespace: capi-system
  workers:
    machineDeployments:
      - class: default-worker
        template:
          metadata:
            labels:
              node-role.kubernetes.io/slave: ''
          bootstrap:
            ref:
              apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
              kind: KubeadmConfigTemplate
              name: kamaji-proxmox
              namespace: capi-system
          infrastructure:
            ref:
              apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
              kind: ProxmoxMachineTemplate
              name: kamaji-proxmox
              namespace: capi-system
      - class: default-worker-gpu
        template:
          metadata:
            labels:
              node-role.kubernetes.io/slave: ''
          bootstrap:
            ref:
              apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
              kind: KubeadmConfigTemplate
              name: kamaji-proxmox
              namespace: capi-system
          infrastructure:
            ref:
              apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
              kind: ProxmoxMachineTemplate
              name: kamaji-proxmox
              namespace: capi-system
