apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: main
  namespace: monitoring
spec:
  alertmanagerConfiguration:
    name: main
  externalUrl: 'https://alertmanager.bealv-mgmt.lan'
