apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: k8s
spec:
  externalLabels:
    cluster: bealv-mgmt
  replicas: 1
  retentionSize: 10GiB
  resources:
    requests:
      cpu: 400m
      memory: 1500Mi
    limits:
      cpu: 1000m
      memory: 1500Mi
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: 'disk-hdd'
        resources:
          requests:
            storage: 20Gi
