apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: addon-controller-role-extra
rules:
  - apiGroups:
      - ''
    resources:
      - configmaps
      - secrets
    verbs:
      - '*'
  - apiGroups:
      - config.projectsveltos.io
    resources:
      - clusterprofiles
      - profiles
    verbs:
      - create
  - apiGroups:
      - ipam.didactiklabs.io
    resources:
      - ipclaims
    verbs:
      - '*'
  - apiGroups:
      - kubernetes.vault.upbound.io
    resources:
      - authbackendconfigs
      - authbackendroles
    verbs:
      - '*'
