apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: projectsveltos
  namespace: projectsveltos
spec:
  interval: 1h0m0s
  chart:
    spec:
      chart: projectsveltos
      version: 0.52.3
      sourceRef:
        kind: HelmRepository
        name: projectsveltos
        namespace: projectsveltos
  values:
    kubernetesClusterDomain: bealv-mgmt.local
    agent:
      managementCluster: true
    registerMgmtClusterJob:
      registerMgmtCluster:
        args:
          - --labels=type=mgmt
