apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-dns-internal
spec:
  refreshInterval: '1h'
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: external-dns-internal
  data:
    - secretKey: api_key
      remoteRef:
        key: secrets/powerdns/server
        property: api_key
