apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pdns-mariadb
spec:
  refreshInterval: '1h'
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: pdns-mariadb
    template:
      engineVersion: v2
      data:
        database_uri: 'mysql://{{ .user }}:{{ .password }}@powerdns-db/{{ .database }}'
        database: '{{ .database }}'
        user: '{{ .user }}'
        password: '{{ .password }}'
  data:
    - secretKey: database
      remoteRef:
        key: secrets/powerdns/mariadb
        property: database
    - secretKey: user
      remoteRef:
        key: secrets/powerdns/mariadb
        property: user
    - secretKey: password
      remoteRef:
        key: secrets/powerdns/mariadb
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: powerdns
spec:
  refreshInterval: '1h'
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: powerdns
  data:
    - secretKey: api_key
      remoteRef:
        key: secrets/powerdns/server
        property: api_key
    - secretKey: webserver_password
      remoteRef:
        key: secrets/powerdns/server
        property: webserver_password
