{
 "title": "Alertmanager / Overview",
 "tags": [ "alertmanager-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(up, cluster)" } },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(alertmanager_alerts{cluster=~\"$cluster\"}, namespace)"
   },
   {
    "name": "service",
    "label": "service",
    "query": "label_values(alertmanager_alerts{cluster=~\"$cluster\"}, service)"
   },
   {
    "name": "integration",
    "query": "label_values(alertmanager_notifications_total{cluster=~\"$cluster\",integration=~\".*\"}, integration)"
   }
  ]
 },
 "panels": [
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Alerts",
   "type": "timeseries",
   "description": "current set of alerts stored in the Alertmanager",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (namespace, service, instance) (\n  alertmanager_alerts{cluster=~\"$cluster\",namespace=~\"$namespace\",service=~\"$service\"}\n)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Alerts receive rate",
   "type": "timeseries",
   "description": "rate of successful and invalid alerts received by the Alertmanager",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (namespace, service, instance) (\n  rate(\n    alertmanager_alerts_received_total{cluster=~\"$cluster\",namespace=~\"$namespace\",service=~\"$service\"}[$__rate_interval]\n  )\n)",
     "legendFormat": "{{instance}} Received"
    },
    {
     "expr": "sum by (namespace, service, instance) (\n  rate(\n    alertmanager_alerts_invalid_total{cluster=~\"$cluster\",namespace=~\"$namespace\",service=~\"$service\"}[$__rate_interval]\n  )\n)",
     "legendFormat": "{{instance}} Invalid"
    }
   ]
  },
  { "title": "Notifications", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "$integration: Notifications Send Rate",
   "type": "timeseries",
   "description": "rate of successful and invalid notifications sent by the Alertmanager",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "repeat": "integration",
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (integration, namespace, service, instance) (\n  rate(\n    alertmanager_notifications_total{cluster=~\"$cluster\",integration=\"$integration\",namespace=~\"$namespace\",service=~\"$service\"}[$__rate_interval]\n  )\n)",
     "legendFormat": "{{instance}} Total"
    },
    {
     "expr": "sum by (integration, namespace, service, instance) (\n  rate(\n    alertmanager_notifications_failed_total{cluster=~\"$cluster\",integration=\"$integration\",namespace=~\"$namespace\",service=~\"$service\"}[$__rate_interval]\n  )\n)",
     "legendFormat": "{{instance}} Failed"
    }
   ]
  },
  {
   "title": "$integration: Notification Duration",
   "type": "timeseries",
   "description": "latency of notifications sent by the Alertmanager",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "repeat": "integration",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le, namespace, service, instance) (\n    rate(\n      alertmanager_notification_latency_seconds_bucket{cluster=~\"$cluster\",integration=\"$integration\",namespace=~\"$namespace\",service=~\"$service\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "{{instance}} 99th Percentile"
    },
    {
     "expr": "histogram_quantile(\n  0.5,\n  sum by (le, namespace, service, instance) (\n    rate(\n      alertmanager_notification_latency_seconds_bucket{cluster=~\"$cluster\",integration=\"$integration\",namespace=~\"$namespace\",service=~\"$service\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "{{instance}} Median"
    },
    {
     "expr": "sum by (namespace, service, instance) (\n    rate(\n      alertmanager_notification_latency_seconds_sum{cluster=~\"$cluster\",integration=\"$integration\",namespace=~\"$namespace\",service=~\"$service\"}[$__rate_interval]\n    )\n  )\n/\n  sum by (namespace, service, instance) (\n    rate(\n      alertmanager_notification_latency_seconds_count{cluster=~\"$cluster\",integration=\"$integration\",namespace=~\"$namespace\",service=~\"$service\"}[$__rate_interval]\n    )\n  )",
     "legendFormat": "{{instance}} Average"
    }
   ]
  }
 ]
}