{
 "title": "Blackbox Exporter (HTTP prober)",
 "description": "Blackbox exporter HTTP prober dashboard",
 "tags": [
  "blackbox",
  "prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(up, cluster)" } },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(probe_success{cluster=~\"$cluster\"}, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(probe_success{cluster=~\"$cluster\",job=~\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "HTTP Probe Overview",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "probe_success{cluster=~\"$cluster\",instance=~\"$instance\",job=~\"$job\"}"
    },
    {
     "expr": "probe_http_ssl{cluster=~\"$cluster\",instance=~\"$instance\",job=~\"$job\"} > 0"
    },
    {
     "expr": "(probe_ssl_earliest_cert_expiry{cluster=~\"$cluster\",instance=~\"$instance\",job=~\"$job\"} - time())\n  /\n    3600\n/\n  24"
    },
    {
     "expr": "probe_http_status_code{cluster=~\"$cluster\",instance=~\"$instance\",job=~\"$job\"} > 0"
    },
    {
     "expr": "avg_over_time(probe_duration_seconds{cluster=~\"$cluster\",instance=~\"$instance\",job=~\"$job\"}[1m])"
    },
    {
     "expr": "probe_tls_version_info{cluster=~\"$cluster\",instance=~\"$instance\",job=~\"$job\"}"
    },
    {
     "expr": "avg_over_time(\n  probe_dns_lookup_time_seconds{cluster=~\"$cluster\",instance=~\"$instance\",job=~\"$job\"}[1m]\n)"
    }
   ]
  },
  {
   "title": "HTTP Probe Duration",
   "type": "graph",
   "description": "Returns how long the probe took to complete in seconds",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (\n  probe_http_duration_seconds{cluster=~\"$cluster\",instance=~\"$instance\",job=~\"$job\"}\n)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "$instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "repeat": "instance",
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Probe Phases Duration",
     "type": "graph",
     "description": "Duration of http request by phase, summed over all redirects",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "probe_http_duration_seconds{cluster=~\"$cluster\",instance=~\"$instance\",job=~\"$job\"}",
       "legendFormat": "{{ phase }}"
      }
     ]
    }
   ]
  }
 ]
}