{
 "title": "Cert-manager-Kubernetes",
 "description": "The dashboard gives an overview of the SSL certs managed by cert-manager in Kubernetes",
 "tags": [
  "k8s",
  "cert-manager"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(certmanager_clock_time_seconds, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(certmanager_certificate_ready_status{cluster=~\"$cluster\"}, exported_namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Valid Certificates",
   "type": "stat",
   "description": "The number if available certificates",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(certmanager_certificate_ready_status{condition=\"True\", cluster=~\"$cluster\", exported_namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Expiring Certificates",
   "type": "stat",
   "description": "The number of certificates that will expire within the next 14 days",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(certmanager_certificate_expiration_timestamp_seconds{cluster=~\"$cluster\", exported_namespace=~\"$namespace\"} < (time()+(14*24*3600)))",
     "legendFormat": "{{exported_namespace}}/{{name}}"
    }
   ]
  },
  {
   "title": "Total ACME Requests",
   "type": "stat",
   "description": "Total number of HTTP requests, based on the selected time range",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(certmanager_http_acme_client_request_count{cluster=~\"$cluster\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time to Expiration (<45 days)",
   "type": "bargauge",
   "description": "Time before the certificates expire. Only shows certificates expiring within 45 days",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(\n      certmanager_certificate_expiration_timestamp_seconds{cluster=~\"$cluster\",exported_namespace=~\"$namespace\"}\n    -\n      time()\n  )\n<\n  45 * (24 * 3600)",
     "legendFormat": "{{cluster}} - {{exported_namespace}} - {{name}}"
    }
   ]
  },
  {
   "title": "Time to Automatic Renewal (<45 days)",
   "type": "bargauge",
   "description": "Time before the certificates are automatically renewed",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(\n      certmanager_certificate_renewal_timestamp_seconds{cluster=~\"$cluster\",exported_namespace=~\"$namespace\"}\n    -\n      time()\n  )\n<\n  45 * (24 * 3600)",
     "legendFormat": "{{cluster}} - {{exported_namespace}} - {{name}}"
    }
   ]
  },
  {
   "title": "Time to Expiration",
   "type": "timeseries",
   "description": "Time before the certificates expire",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "targets": [
    {
     "expr": "(\n      certmanager_certificate_expiration_timestamp_seconds{cluster=~\"$cluster\",exported_namespace=~\"$namespace\"}\n    -\n      time()\n  )\n/\n  (24 * 3600)",
     "legendFormat": "{{cluster}} - {{exported_namespace}} - {{name}}"
    }
   ]
  },
  {
   "title": "Certificate Renewal Events",
   "type": "timeseries",
   "description": "Displays the timestamp of a renewal, based on the expiration time changing",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "changes(certmanager_certificate_renewal_timestamp_seconds{cluster=~\"$cluster\", exported_namespace=~\"$namespace\"}[15m]) > 0",
     "legendFormat": "{{cluster}} - {{exported_namespace}} - {{name}}"
    }
   ]
  },
  {
   "title": "ACME Requests by Cluster",
   "type": "barchart",
   "description": "Total number of HTTP requests, based on the selected range",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sort_desc(sum by (cluster)(increase(certmanager_http_acme_client_request_count{cluster=~\"$cluster\"}[$__range]))) > 0",
     "legendFormat": "{{cluster}}"
    }
   ]
  }
 ]
}