{
 "title": "Kubernetes / Overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(up, cluster)" } }
  ]
 },
 "panels": [
  { "title": "Cluster Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Control Plane Status",
   "type": "stat",
   "description": "Indicates whether API Server, Scheduler or Controller manager is down.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(up{cluster=~\"$cluster\",job=~\"apiserver|kube-scheduler|kube-controller-manager\"} == 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Unschedulable",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_spec_unschedulable{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Memory Pressure",
   "type": "stat",
   "description": "This is true if there is insufficient memory on the node, which could cause the node to swap frequently.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{cluster=~\"$cluster\",condition=\"MemoryPressure\",status!=\"false\"})"
    }
   ]
  },
  {
   "title": "Disk Pressure",
   "type": "stat",
   "description": "This condition is true if there is insufficient disk space on the node.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{cluster=~\"$cluster\",condition=\"DiskPressure\",status!=\"false\"})"
    }
   ]
  },
  {
   "title": "PID Pressure",
   "type": "stat",
   "description": "True when there are too many processes running on the node, indicating a potential exhaustion of process identifiers (PIDs).",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{cluster=~\"$cluster\",condition=\"PIDPressure\",status!=\"false\"})"
    }
   ]
  },
  {
   "title": "Network Unavailable",
   "type": "stat",
   "description": "Indicates that the network to the node is not correctly configured or not available.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{cluster=~\"$cluster\",condition=\"NetworkUnavailable\",status!=\"false\"})"
    }
   ]
  },
  {
   "title": "Node Not Ready",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{cluster=~\"$cluster\",condition=\"Ready\",status!=\"true\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Pods",
   "type": "stat",
   "description": "Indicates that there are pods in failed phase",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{cluster=~\"$cluster\",phase=\"Failed\"})"
    }
   ]
  },
  {
   "title": "Unknown Pods",
   "type": "stat",
   "description": "Indicates that there are pods in unknown phase",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{cluster=~\"$cluster\",phase=\"Unknown\"})"
    }
   ]
  },
  {
   "title": "Unscheduled Pods",
   "type": "stat",
   "description": "Indicates that there are pods that cannot be scheduled.",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max_over_time(kube_pod_status_scheduled{cluster=~\"$cluster\",condition=\"false\"}[5m]))"
    }
   ]
  },
  {
   "title": "PVCs Above 80%",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(\n      max by (persistentvolumeclaim, namespace) (kubelet_volume_stats_used_bytes{cluster=~\"$cluster\"})\n    and\n          (max by (persistentvolumeclaim, namespace) (kubelet_volume_stats_used_bytes{cluster=~\"$cluster\"}))\n        /\n          (\n            max by (persistentvolumeclaim, namespace) (kubelet_volume_stats_capacity_bytes{cluster=~\"$cluster\"})\n          )\n      >=\n        (80 / 100)\n  )\nor\n  vector(0)"
    }
   ]
  },
  {
   "title": "PVCs in Pending State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count((kube_persistentvolumeclaim_status_phase{cluster=~\"$cluster\",phase=\"Pending\"} == 1))\nor\n  vector(0)"
    }
   ]
  },
  {
   "title": "PVCs in Lost State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count((kube_persistentvolumeclaim_status_phase{cluster=~\"$cluster\",phase=\"Lost\"} == 1)) or vector(0)"
    }
   ]
  },
  {
   "title": "Cluster Resource Count",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kubernetes Resource Count",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (namespace) (kube_pod_info{cluster=~\"$cluster\"})",
       "legendFormat": "{{namespace}} / Running Pods"
      },
      {
       "expr": "sum by (namespace) (kube_service_info{cluster=~\"$cluster\"})",
       "legendFormat": "{{namespace}} / Services"
      },
      {
       "expr": "sum by (namespace) (kube_ingress_info{cluster=~\"$cluster\"})",
       "legendFormat": "{{namespace}} / Ingresses"
      },
      {
       "expr": "sum by (namespace) (kube_deployment_labels{cluster=~\"$cluster\"})",
       "legendFormat": "{{namespace}} / Deployments"
      },
      {
       "expr": "sum by (namespace) (kube_statefulset_labels{cluster=~\"$cluster\"})",
       "legendFormat": "{{namespace}} / Statefulsets"
      },
      {
       "expr": "sum by (namespace) (kube_daemonset_labels{cluster=~\"$cluster\"})",
       "legendFormat": "{{namespace}} / Daemonsets"
      },
      {
       "expr": "sum by (namespace) (kube_persistentvolumeclaim_info{cluster=~\"$cluster\"})",
       "legendFormat": "{{namespace}} / Persistent Volume Claims"
      },
      {
       "expr": "sum by (namespace) (kube_hpa_labels{cluster=~\"$cluster\"})",
       "legendFormat": "{{namespace}} / Horizontal Pod Autoscalers"
      },
      {
       "expr": "sum by (namespace) (kube_configmap_info{cluster=~\"$cluster\"})",
       "legendFormat": "{{namespace}} / Configmaps"
      },
      {
       "expr": "sum by (namespace) (kube_secret_info{cluster=~\"$cluster\"})",
       "legendFormat": "{{namespace}} / Secrets"
      },
      {
       "expr": "sum by (namespace) (kube_networkpolicy_labels{cluster=~\"$cluster\"})",
       "legendFormat": "{{namespace}} / Network Policies "
      }
     ]
    }
   ]
  },
  {
   "title": "Global",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Global CPU  Usage",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 108 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(1 - rate(node_cpu_seconds_total{cluster=~\"$cluster\",job=\"node-exporter\",mode=\"idle\"}[$__rate_interval]))\n/\n  sum(machine_cpu_cores{cluster=~\"$cluster\"})",
       "legendFormat": "Real"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{cluster=~\"$cluster\",unit=\"core\"})\n/\n  sum(machine_cpu_cores{cluster=~\"$cluster\"})",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{cluster=~\"$cluster\",unit=\"core\"})\n/\n  sum(machine_cpu_cores{cluster=~\"$cluster\"})",
       "legendFormat": "Limits"
      }
     ]
    },
    {
     "title": "Global RAM Usage",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 108 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(\n    sum(\n        node_memory_MemTotal_bytes{cluster=~\"$cluster\",job=\"node-exporter\"}\n      -\n        node_memory_MemAvailable_bytes{cluster=~\"$cluster\",job=\"node-exporter\"}\n    )\n  )\n/\n  sum(machine_memory_bytes{cluster=~\"$cluster\"})",
       "legendFormat": "Real"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{cluster=~\"$cluster\",unit=\"byte\"})\n/\n  sum(machine_memory_bytes{cluster=~\"$cluster\"})",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{cluster=~\"$cluster\",unit=\"byte\"})\n/\n  sum(machine_memory_bytes{cluster=~\"$cluster\"})",
       "legendFormat": "Limits"
      }
     ]
    },
    {
     "title": "Cluster Utilization",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 108 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg(\n  sum by (instance, cpu) (\n    rate(node_cpu_seconds_total{cluster=~\"$cluster\",mode!~\"idle|iowait|steal\"}[5m])\n  )\n)",
       "legendFormat": "CPU Usage (%)"
      },
      {
       "expr": "sum(\n      node_memory_MemTotal_bytes{cluster=~\"$cluster\"}\n    -\n      node_memory_MemAvailable_bytes{cluster=~\"$cluster\"}\n  )\n/\n  sum(node_memory_MemTotal_bytes{cluster=~\"$cluster\"})",
       "legendFormat": "Mem Usage (%)"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 116 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(1 - rate(node_cpu_seconds_total{cluster=~\"$cluster\",job=\"node-exporter\",mode=\"idle\"}[$__rate_interval]))",
       "legendFormat": "Real"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{cluster=~\"$cluster\",unit=\"core\"})",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{cluster=~\"$cluster\",unit=\"core\"})",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum(machine_cpu_cores{cluster=~\"$cluster\"})",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "RAM Usage",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 116 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(\n    node_memory_MemTotal_bytes{cluster=~\"$cluster\",job=\"node-exporter\"}\n  -\n    node_memory_MemAvailable_bytes{cluster=~\"$cluster\",job=\"node-exporter\"}\n)",
       "legendFormat": "Real"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{cluster=~\"$cluster\",unit=\"byte\"})",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{cluster=~\"$cluster\",unit=\"byte\"})",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum(machine_memory_bytes{cluster=~\"$cluster\"})",
       "legendFormat": "Total"
      }
     ]
    }
   ]
  },
  { "title": "Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Health Status by Node",
   "type": "table",
   "description": "This table shows health status of nodes.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (node) (kube_node_spec_unschedulable{cluster=~\"$cluster\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (node) (kube_node_status_condition{cluster=~\"$cluster\",condition=\"Ready\",status!=\"true\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (node) (\n  kube_node_status_condition{cluster=~\"$cluster\",condition=\"DiskPressure\",status!=\"false\"}\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (node) (\n  kube_node_status_condition{cluster=~\"$cluster\",condition=\"MemoryPressure\",status!=\"false\"}\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (node) (\n  kube_node_status_condition{cluster=~\"$cluster\",condition=\"PIDPressure\",status!=\"false\"}\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (node) (\n  kube_node_status_condition{cluster=~\"$cluster\",condition=\"NetworkUnavailable\",status!=\"false\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nodes information",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "count by (node) (kube_pod_info{cluster=~\"$cluster\",created_by_kind!~\"<none>|Job\",node=~\"^$Node$\"})",
     "legendFormat": "number of pods"
    },
    {
     "expr": "sum by (node) (irate(container_cpu_usage_seconds_total{cluster=~\"$cluster\",container!=\"\"}[2m]))"
    },
    {
     "expr": "kube_node_status_allocatable{cluster=~\"$cluster\",resource=\"cpu\",unit=\"core\"} - 0"
    },
    {
     "expr": "sum by (node) (kube_pod_container_resource_requests{cluster=~\"$cluster\",resource=\"cpu\",unit=\"core\"})"
    },
    {
     "expr": "sum by (node) (kube_pod_container_resource_limits{cluster=~\"$cluster\",resource=\"cpu\",unit=\"core\"})"
    },
    {
     "expr": "sum by (node) (container_memory_working_set_bytes{cluster=~\"$cluster\",container!=\"\"})"
    },
    {
     "expr": "sum by (node) (kube_node_status_allocatable{cluster=~\"$cluster\",resource=\"memory\",unit=\"byte\"}) - 0"
    },
    {
     "expr": "sum by (node) (\n  kube_pod_container_resource_requests{cluster=~\"$cluster\",resource=\"memory\",unit=\"byte\"}\n)"
    },
    {
     "expr": "sum by (node) (\n  kube_pod_container_resource_limits{cluster=~\"$cluster\",resource=\"memory\",unit=\"byte\"}\n)"
    },
    {
     "expr": "sum by (node) (container_fs_usage_bytes{cluster=~\"$cluster\",device=~\"^/dev/.*$\",id=\"/\"})"
    },
    {
     "expr": "sum by (node) (container_fs_limit_bytes{cluster=~\"$cluster\",device=~\"^/dev/.*$\",id=\"/\"})"
    },
    {
     "expr": "sum by (node) (container_memory_working_set_bytes{cluster=~\"$cluster\",container!=\"\"})\n/\n  sum by (node) (kube_node_status_allocatable{cluster=~\"$cluster\",resource=\"memory\",unit=\"byte\"})",
     "legendFormat": "Memory usage%"
    },
    {
     "expr": "sum by (node) (\n    kube_pod_container_resource_requests{cluster=~\"$cluster\",resource=\"memory\",unit=\"byte\"}\n  )\n/\n  sum by (node) (kube_node_status_allocatable{cluster=~\"$cluster\",resource=\"memory\",unit=\"byte\"})",
     "legendFormat": "Memory request%"
    },
    {
     "expr": "sum by (node) (\n    kube_pod_container_resource_limits{cluster=~\"$cluster\",resource=\"memory\",unit=\"byte\"}\n  )\n/\n  sum by (node) (kube_node_status_allocatable{cluster=~\"$cluster\",resource=\"memory\",unit=\"byte\"})",
     "legendFormat": "Memory limit %"
    },
    {
     "expr": "sum by (node) (irate(container_cpu_usage_seconds_total{cluster=~\"$cluster\",container!=\"\"}[2m]))\n/\n  sum by (node) (kube_node_status_allocatable{cluster=~\"$cluster\",resource=\"cpu\",unit=\"core\"})",
     "legendFormat": "CPU usage %"
    },
    {
     "expr": "sum by (node) (kube_pod_container_resource_requests{cluster=~\"$cluster\",resource=\"cpu\",unit=\"core\"})\n/\n  sum by (node) (kube_node_status_allocatable{cluster=~\"$cluster\",resource=\"cpu\",unit=\"core\"})",
     "legendFormat": "CPU request %"
    },
    {
     "expr": "sum by (node) (kube_pod_container_resource_limits{cluster=~\"$cluster\",resource=\"cpu\",unit=\"core\"})\n/\n  sum by (node) (kube_node_status_allocatable{cluster=~\"$cluster\",resource=\"cpu\",unit=\"core\"})",
     "legendFormat": "Memory limit %"
    },
    {
     "expr": "sum by (node) (container_fs_usage_bytes{cluster=~\"$cluster\",device=~\"^/dev/.*$\",id=\"/\"})\n/\n  sum by (node) (container_fs_limit_bytes{cluster=~\"$cluster\",device=~\"^/dev/.*$\",id=\"/\"})",
     "legendFormat": "Disk usage %"
    },
    {
     "expr": "sum by (node) (kube_node_status_allocatable{cluster=~\"$cluster\",resource=\"pods\",unit=\"integer\"})",
     "legendFormat": "Pod limit"
    }
   ]
  },
  {
   "title": "Node CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (node) (irate(container_cpu_usage_seconds_total{cluster=~\"$cluster\",container!=\"\"}[2m]))\n  /\n    sum by (node) (kube_node_status_allocatable{cluster=~\"$cluster\",resource=\"cpu\",unit=\"core\"})\n*\n  100",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Node Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (node) (container_memory_working_set_bytes{cluster=~\"$cluster\",container!=\"\"})\n  /\n    sum by (node) (kube_node_status_allocatable{cluster=~\"$cluster\",resource=\"memory\",unit=\"byte\"})\n*\n  100",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Disk (Free)",
   "type": "table",
   "description": "The table shows available disk size by mount points. Only mount point that used over 50% are displayed.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "sum by (instance, fstype, mountpoint) (node_filesystem_free_bytes{cluster=~\"$cluster\",fstype!=\"\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (instance, fstype, mountpoint) (\n  node_filesystem_size_bytes{cluster=~\"$cluster\",fstype!=\"\",job=\"node-exporter\",mountpoint!=\"\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Namespaces",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods Status",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "sum by (namespace) (kube_pod_owner{cluster=~\"$cluster\",job=\"kube-state-metrics\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "count by (namespace) (\n  avg by (workload, namespace) (namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\"})\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (namespace) (kube_pod_status_phase{cluster=~\"$cluster\",phase=\"Failed\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (namespace) (kube_pod_status_phase{cluster=~\"$cluster\",phase=\"Unknown\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (namespace) (\n  avg_over_time(kube_pod_status_scheduled{cluster=~\"$cluster\",condition=\"false\"}[5m])\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Quota",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (namespace) (\n  container_memory_rss{cluster=~\"$cluster\",container!=\"\",job=\"kubelet\",metrics_path=\"/metrics/cadvisor\"}\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (namespace) (namespace_memory:kube_pod_container_resource_requests:sum{cluster=~\"$cluster\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (namespace) (\n    container_memory_rss{cluster=~\"$cluster\",container!=\"\",job=\"kubelet\",metrics_path=\"/metrics/cadvisor\"}\n  )\n/\n  sum by (namespace) (namespace_memory:kube_pod_container_resource_requests:sum{cluster=~\"$cluster\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (namespace) (namespace_memory:kube_pod_container_resource_limits:sum{cluster=~\"$cluster\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (namespace) (\n    container_memory_rss{cluster=~\"$cluster\",container!=\"\",job=\"kubelet\",metrics_path=\"/metrics/cadvisor\"}\n  )\n/\n  sum by (namespace) (namespace_memory:kube_pod_container_resource_limits:sum{cluster=~\"$cluster\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU Quota",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (namespace) (\n  node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=~\"$cluster\"}\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (namespace) (namespace_cpu:kube_pod_container_resource_requests:sum{cluster=~\"$cluster\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (namespace) (\n    node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=~\"$cluster\"}\n  )\n/\n  sum by (namespace) (namespace_cpu:kube_pod_container_resource_requests:sum{cluster=~\"$cluster\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (namespace) (namespace_cpu:kube_pod_container_resource_limits:sum{cluster=~\"$cluster\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (namespace) (\n    node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=~\"$cluster\"}\n  )\n/\n  sum by (namespace) (namespace_cpu:kube_pod_container_resource_limits:sum{cluster=~\"$cluster\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Workloads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Quota",
     "type": "table-old",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 191 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count by (workload, workload_type, namespace) (\n  namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\"}\n)"
      },
      {
       "expr": "sum by (workload, workload_type) (\n    node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=~\"$cluster\"}\n  * on (namespace, pod) group_left (workload, workload_type)\n    namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\"}\n)"
      },
      {
       "expr": "sum by (workload, workload_type) (\n    kube_pod_container_resource_requests{cluster=~\"$cluster\",job=\"kube-state-metrics\",resource=\"cpu\"}\n  * on (namespace, pod) group_left (workload, workload_type)\n    namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\"}\n)"
      },
      {
       "expr": "sum by (workload, workload_type, namespace) (\n      node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=~\"$cluster\"}\n    * on (namespace, pod) group_left (workload, workload_type)\n      namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\"}\n  )\n/\n  sum by (workload, workload_type, namespace) (\n      kube_pod_container_resource_requests{cluster=~\"$cluster\",job=\"kube-state-metrics\",resource=\"cpu\"}\n    * on (namespace, pod) group_left (workload, workload_type)\n      namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\"}\n  )"
      },
      {
       "expr": "sum by (workload, workload_type) (\n    kube_pod_container_resource_limits{cluster=~\"$cluster\",job=\"kube-state-metrics\",resource=\"cpu\"}\n  * on (namespace, pod) group_left (workload, workload_type)\n    namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\"}\n)"
      },
      {
       "expr": "sum by (workload, workload_type) (\n      node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=~\"$cluster\"}\n    * on (namespace, pod) group_left (workload, workload_type)\n      namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\"}\n  )\n/\n  sum by (workload, workload_type) (\n      kube_pod_container_resource_limits{cluster=~\"$cluster\",job=\"kube-state-metrics\",resource=\"cpu\"}\n    * on (namespace, pod) group_left (workload, workload_type)\n      namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\"}\n  )"
      }
     ]
    },
    {
     "title": "Memory Quota",
     "type": "table-old",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 201 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count by (workload, workload_type, namespace) (\n  namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\"}\n)"
      },
      {
       "expr": "sum by (workload, workload_type) (\n    container_memory_working_set_bytes{cluster=~\"$cluster\",container!=\"\",image!=\"\",job=\"kubelet\"}\n  * on (namespace, pod) group_left (workload, workload_type)\n    namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\"}\n)"
      },
      {
       "expr": "sum by (workload, workload_type) (\n    kube_pod_container_resource_requests{cluster=~\"$cluster\",job=\"kube-state-metrics\",resource=\"memory\"}\n  * on (namespace, pod) group_left (workload, workload_type)\n    namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\"}\n)"
      },
      {
       "expr": "sum by (workload, workload_type) (\n      container_memory_working_set_bytes{cluster=~\"$cluster\",container!=\"\",image!=\"\",job=\"kubelet\"}\n    * on (namespace, pod) group_left (workload, workload_type)\n      namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\"}\n  )\n/\n  sum by (workload, workload_type) (\n      kube_pod_container_resource_requests{cluster=~\"$cluster\",job=\"kube-state-metrics\",resource=\"memory\"}\n    * on (namespace, pod) group_left (workload, workload_type)\n      namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\"}\n  )"
      },
      {
       "expr": "sum by (workload, workload_type) (\n    kube_pod_container_resource_limits{cluster=~\"$cluster\",job=\"kube-state-metrics\",resource=\"memory\"}\n  * on (namespace, pod) group_left (workload, workload_type)\n    namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\"}\n)"
      },
      {
       "expr": "sum by (workload, workload_type) (\n      container_memory_working_set_bytes{cluster=~\"$cluster\",container!=\"\",image!=\"\",job=\"kubelet\"}\n    * on (namespace, pod) group_left (workload, workload_type)\n      namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\"}\n  )\n/\n  sum by (workload, workload_type) (\n      kube_pod_container_resource_limits{cluster=~\"$cluster\",job=\"kube-state-metrics\",resource=\"memory\"}\n    * on (namespace, pod) group_left (workload, workload_type)\n      namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\"}\n  )"
      }
     ]
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "collapsed": true,
   "panels": [
    {
     "title": "Jobs Succeeded",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_job_status_succeeded{cluster=~\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Job last success time from now",
     "type": "table-old",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 22 },
     "targets": [
      {
       "expr": "(time() - kube_job_status_completion_time{cluster=~\"$cluster\"}) / 60 / 60 / 24 > 1",
       "legendFormat": "{{job_name}}"
      }
     ]
    },
    {
     "title": "Job failed",
     "type": "table-old",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 22 },
     "targets": [
      {
       "expr": "kube_job_status_failed{cluster=~\"$cluster\"} > 1",
       "legendFormat": "{{job_name}}"
      }
     ]
    },
    {
     "title": "Jobs Active",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_job_status_active{cluster=~\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Jobs Failed",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_job_status_failed{cluster=~\"$cluster\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Pods",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Quota",
     "type": "table",
     "description": "This table shows the CPU quota of pods in a namespace, shows only those that there CPU Requests (%) is greater then 80% and CPU Limits (%) is greater then 60%",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (namespace, pod) (\n  node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=~\"$cluster\"}\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (namespace, pod) (\n  cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{cluster=~\"$cluster\"}\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (namespace, pod) (\n    node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=~\"$cluster\"}\n  )\n/\n  sum by (namespace, pod) (\n    cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{cluster=~\"$cluster\"}\n  )",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (namespace, pod) (\n  cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{cluster=~\"$cluster\"}\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (namespace, pod) (\n    node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=~\"$cluster\"}\n  )\n/\n  sum by (namespace, pod) (\n    cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{cluster=~\"$cluster\"}\n  )",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Quota",
     "type": "table",
     "description": "This table shows the Memory quota of pods in a namespace, shows only those that there Memory Requests (%) is greater then 80% and Memory Limits (%) is greater then 60%",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (namespace, pod) (\n  container_memory_working_set_bytes{cluster=~\"$cluster\",container!=\"\",image!=\"\",job=\"kubelet\",metrics_path=\"/metrics/cadvisor\"}\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (namespace, pod) (\n  cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{cluster=~\"$cluster\"}\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (namespace, pod) (\n    container_memory_working_set_bytes{cluster=~\"$cluster\",container!=\"\",image!=\"\",job=\"kubelet\",metrics_path=\"/metrics/cadvisor\"}\n  )\n/\n  sum by (namespace, pod) (\n    cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{cluster=~\"$cluster\"}\n  )",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (namespace, pod) (\n  cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{cluster=~\"$cluster\"}\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (namespace, pod) (\n    container_memory_working_set_bytes{cluster=~\"$cluster\",container!=\"\",image!=\"\",job=\"kubelet\",metrics_path=\"/metrics/cadvisor\"}\n  )\n/\n  sum by (namespace, pod) (\n    cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{cluster=~\"$cluster\"}\n  )",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Volumes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "PVC Overview",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (persistentvolumeclaim, namespace, storageclass, volumename) (\n  kube_persistentvolumeclaim_info{cluster=~\"$cluster\"}\n)"
    },
    {
     "expr": "sum by (persistentvolumeclaim) (\n  kubelet_volume_stats_capacity_bytes{cluster=~\"$cluster\"} / 1024 / 1024 / 1024\n)"
    },
    {
     "expr": "sum by (persistentvolumeclaim) (\n  kubelet_volume_stats_used_bytes{cluster=~\"$cluster\"} / 1024 / 1024 / 1024\n)"
    },
    {
     "expr": "sum by (persistentvolumeclaim) (\n  kubelet_volume_stats_available_bytes{cluster=~\"$cluster\"} / 1024 / 1024 / 1024\n)"
    },
    {
     "expr": "sum by (persistentvolumeclaim) (\n    kube_persistentvolumeclaim_status_phase{cluster=~\"$cluster\",phase=~\"(Pending|Lost)\"}\n  )\n+\n  sum by (persistentvolumeclaim) (\n    kube_persistentvolumeclaim_status_phase{cluster=~\"$cluster\",phase=~\"(Lost)\"}\n  )"
    },
    {
     "expr": "sum by (persistentvolumeclaim) (\n      kubelet_volume_stats_used_bytes{cluster=~\"$cluster\"}\n    /\n      kubelet_volume_stats_capacity_bytes{cluster=~\"$cluster\"}\n  *\n    100\n)"
    }
   ]
  },
  {
   "title": "All Running PVCs Used Bytes",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(max by (persistentvolumeclaim, namespace) (kubelet_volume_stats_used_bytes{cluster=~\"$cluster\"}))",
     "legendFormat": "{{namespace}} ({{persistentvolumeclaim}})"
    }
   ]
  },
  {
   "title": "Daily Volume Use Rate",
   "type": "graph",
   "description": "WARNING: Any PVCs that are not bound to a running pod will not show up in this state.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(kubelet_volume_stats_used_bytes{cluster=~\"$cluster\"}[1d])",
     "legendFormat": "{{namespace}} ({{persistentvolumeclaim}})"
    }
   ]
  },
  {
   "title": "API Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 },
   "collapsed": true,
   "panels": [
    {
     "title": "Health Status",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "up{cluster=~\"$cluster\",job=\"apiserver\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Deprecated Kubernetes Resources",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "apiserver_requested_deprecated_apis{cluster=~\"$cluster\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Summary by Instance",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "sum by (instance) (rate(process_cpu_seconds_total{cluster=~\"$cluster\",job=\"apiserver\"}[5m]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (instance) (process_resident_memory_bytes{cluster=~\"$cluster\",job=\"apiserver\"})\n/\n  (1024 * 1024 * 1024)",
       "legendFormat": "Mem Usage (GiB)"
      },
      {
       "expr": "sum by (instance) (\n    rate(apiserver_request_duration_seconds_bucket{cluster=~\"$cluster\",job=\"apiserver\"}[5m])\n  )\n/\n  1000",
       "legendFormat": "Request Duration (s)"
      },
      {
       "expr": "sum by (instance) (\n  rate(apiserver_request_total{cluster=~\"$cluster\",code=~\"5..\",job=\"apiserver\"}[5m])\n)",
       "legendFormat": "Error Rate Last 5min (e/s)"
      },
      {
       "expr": "sum by (instance) (rate(workqueue_depth{cluster=~\"$cluster\",job=\"apiserver\"}[5m]))",
       "legendFormat": "Work Queue"
      }
     ]
    },
    {
     "title": "Summary by Verb",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "sum by (verb) (rate(apiserver_request_total{cluster=~\"$cluster\"}[5m])) or on () vector(0)",
       "legendFormat": "Requests (req/s)"
      },
      {
       "expr": "sum by (verb) (\n    rate(apiserver_request_duration_seconds_bucket{cluster=~\"$cluster\",job=\"apiserver\"}[5m])\n  )\nor on ()\n  vector(0)",
       "legendFormat": "Request Latency (ms)"
      },
      {
       "expr": "sum by (verb) (rate(apiserver_request_total{cluster=~\"$cluster\",code=~\"5..\",job=\"apiserver\"}[5m]))\n  /\n    sum by (verb) (rate(apiserver_request_total{cluster=~\"$cluster\",job=\"apiserver\"}[5m]))\nor on ()\n  vector(0)",
       "legendFormat": "Error Rate Last 5min (e/s)"
      }
     ]
    }
   ]
  }
 ]
}