{
 "title": "Contour Ingress Metrics",
 "description": "This Grafana dashboard comprehensively monitors the Project Contour Ingress Controller at the service and namespace level (Projectcontour)",
 "tags": [
  "projectcontour",
  "ingress"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(up, cluster)" } },
   {
    "name": "contour_namespace",
    "label": "Contour Namespace",
    "query": {
     "query": "label_values(contour_build_info{cluster=~\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(envoy_cluster_update_time{cluster=~\"$cluster\",namespace=\"$contour_namespace\"}, envoy_cluster_name)"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(envoy_cluster_update_time{cluster=~\"$cluster\",envoy_cluster_name=~\"${namespace}_[a-z\\\\-]+_\\\\d+\"}, envoy_cluster_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests (period)",
   "type": "stat",
   "description": "This is the total number of requests made in this period (top-right period selected)",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    envoy_cluster_upstream_rq_total{cluster=~\"$cluster\",envoy_cluster_name=~\"${namespace}_${service}_\\\\d+\",namespace=\"${contour_namespace}\"}[${__range_s}s]\n  )\n)"
    }
   ]
  },
  {
   "title": "Connections (period)",
   "type": "stat",
   "description": "This is the total number of connections made in this period (top-right period selected)",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    envoy_cluster_upstream_cx_total{cluster=~\"$cluster\",envoy_cluster_name=~\"${namespace}_${service}_\\\\d+\",namespace=\"${contour_namespace}\"}[${__range_s}s]\n  )\n)"
    }
   ]
  },
  {
   "title": "% Success (period)",
   "type": "stat",
   "description": "This is the percentage of successful requests over the entire period in the top-right hand corner.\n\nNOTE: Ignoring 404s in this metric, since a 404 is a normal response for errant/invalid request. ",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    rate(\n      envoy_cluster_upstream_rq_xx{cluster=~\"$cluster\",envoy_cluster_name=~\"${namespace}_${service}_\\\\d+\",envoy_response_code_class!~\"4|5\",namespace=\"${contour_namespace}\"}[${__range_s}s]\n    )\n  )\n/\n  (\n      sum(\n        rate(\n          envoy_cluster_upstream_rq_xx{cluster=~\"$cluster\",envoy_cluster_name=~\"${namespace}_${service}_\\\\d+\",namespace=\"${contour_namespace}\"}[${__range_s}s]\n        )\n      )\n    -\n      (\n          sum(\n            rate(\n              envoy_cluster_upstream_rq{cluster=~\"$cluster\",envoy_cluster_name=~\"${namespace}_${service}_\\\\d+\",envoy_response_code=~\"404\",namespace=\"${contour_namespace}\"}[${__range_s}s]\n            )\n          )\n        or\n          vector(0)\n      )\n  )"
    }
   ]
  },
  {
   "title": "HTTP 1/2xx (5m)",
   "type": "stat",
   "description": "This is the number of successful requests in the last five minutes.  Successful being 1xx or 2xx by the standard HTTP definition.",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    increase(\n      envoy_cluster_upstream_rq_xx{cluster=~\"$cluster\",envoy_cluster_name=~\"${namespace}_${service}_\\\\d+\",envoy_response_code_class=~\"1|2\",namespace=~\"${contour_namespace}\"}[5m]\n    )\n  )\nor\n  vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP 5xx (5m)",
   "type": "stat",
   "description": "This is the number of 5xx requests in the last five minutes.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    increase(\n      envoy_cluster_upstream_rq_xx{cluster=~\"$cluster\",envoy_cluster_name=~\"${namespace}_${service}_\\\\d+\",envoy_response_code_class=\"5\",namespace=~\"${contour_namespace}\"}[5m]\n    )\n  )\nor\n  vector(0)"
    }
   ]
  },
  {
   "title": "Reqs (5m)",
   "type": "stat",
   "description": "The number of HTTP requests made in the last five minute window",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    envoy_cluster_upstream_rq_total{cluster=~\"$cluster\",envoy_cluster_name=~\"${namespace}_${service}_\\\\d+\",namespace=~\"${contour_namespace}\"}[5m]\n  )\n)"
    }
   ]
  },
  {
   "title": "Conns (5m)",
   "type": "stat",
   "description": "This is the number of new connections made to the ingress in the last five minutes.",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    envoy_cluster_upstream_cx_total{cluster=~\"$cluster\",envoy_cluster_name=~\"${namespace}_${service}_\\\\d+\",namespace=~\"${contour_namespace}\"}[5m]\n  )\n)"
    }
   ]
  },
  {
   "title": "% Success (5m)",
   "type": "stat",
   "description": "This is the percentage of successful requests over the last five minutes.\n\nNOTE: Ignoring 404s,  in this metric, since a  404 is a normal response for errant requests",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    rate(\n      envoy_cluster_upstream_rq_xx{cluster=~\"$cluster\",envoy_cluster_name=~\"${namespace}_${service}_\\\\d+\",envoy_response_code_class!~\"4|5\",namespace=\"${contour_namespace}\"}[5m]\n    )\n  )\n/\n  (\n      sum(\n        rate(\n          envoy_cluster_upstream_rq_xx{cluster=~\"$cluster\",envoy_cluster_name=~\"${namespace}_${service}_\\\\d+\",namespace=\"${contour_namespace}\"}[5m]\n        )\n      )\n    -\n      (\n          sum(\n            rate(\n              envoy_cluster_upstream_rq{cluster=~\"$cluster\",envoy_cluster_name=~\"${namespace}_${service}_\\\\d+\",envoy_response_code=~\"404\",namespace=\"${contour_namespace}\"}[5m]\n            )\n          )\n        or\n          vector(0)\n      )\n  )"
    }
   ]
  },
  {
   "title": "HTTP 3xx (5m)",
   "type": "stat",
   "description": "This is the number of 3xx requests in the last five minutes.",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    increase(\n      envoy_cluster_upstream_rq_xx{cluster=~\"$cluster\",envoy_cluster_name=~\"${namespace}_${service}_\\\\d+\",envoy_response_code_class=\"3\",namespace=~\"${contour_namespace}\"}[5m]\n    )\n  )\nor\n  vector(0)"
    }
   ]
  },
  {
   "title": "HTTP 4xx (5m)",
   "type": "stat",
   "description": "This is the number of 4xx requests in the last five minutes.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    increase(\n      envoy_cluster_upstream_rq_xx{cluster=~\"$cluster\",envoy_cluster_name=~\"${namespace}_${service}_\\\\d+\",envoy_response_code_class=\"4\",namespace=~\"${contour_namespace}\"}[5m]\n    )\n  )\nor\n  vector(0)"
    }
   ]
  },
  {
   "title": "Upstream members",
   "type": "stat",
   "description": "The number of healthy replicas of the upstream service members",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\n    sum by (envoy_cluster_name) (\n      envoy_cluster_membership_healthy{cluster=~\"$cluster\",envoy_cluster_name=~\"${namespace}_${service}_\\\\d+\",namespace=\"${contour_namespace}\"}\n    )\n  /\n    count by (envoy_cluster_name) (\n      envoy_cluster_membership_healthy{cluster=~\"$cluster\",envoy_cluster_name=~\"${namespace}_${service}_\\\\d+\",namespace=\"${contour_namespace}\"}\n    ),\n  \"ingress\",\n  \"$1/$2\",\n  \"envoy_cluster_name\",\n  \"^([a-z\\\\-]+)_([a-z\\\\-]+)_\\\\d+$\"\n)",
     "legendFormat": "{{ingress}}"
    }
   ]
  },
  { "title": "Request Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Ingress Success Requests (non 4|5xx Responses)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (envoy_response_code, ingress) (\n  label_replace(\n    rate(\n      envoy_cluster_upstream_rq{cluster=~\"$cluster\",envoy_cluster_name=~\"${namespace}_${service}_\\\\d+\",envoy_response_code=~\"[^45].*\",namespace=\"${contour_namespace}\"}[1m]\n    ),\n    \"ingress\",\n    \"$1/$2\",\n    \"envoy_cluster_name\",\n    \"^([a-z\\\\-]+)_([a-z\\\\-]+)_\\\\d+$\"\n  )\n)",
     "legendFormat": "{{ingress}} - {{envoy_response_code}}"
    }
   ]
  },
  {
   "title": "Ingress Failed Requests (4|5xx Responses)",
   "type": "timeseries",
   "description": "NOTE: Showing 404s in this metric",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (envoy_response_code, ingress) (\n  label_replace(\n    rate(\n      envoy_cluster_upstream_rq{cluster=~\"$cluster\",envoy_cluster_name=~\"${namespace}_${service}_\\\\d+\",envoy_response_code=~\"[45].*\",namespace=\"${contour_namespace}\"}[1m]\n    ),\n    \"ingress\",\n    \"$1/$2\",\n    \"envoy_cluster_name\",\n    \"^([a-z\\\\-]+)_([a-z\\\\-]+)_\\\\d+$\"\n  )\n)",
     "legendFormat": "{{ingress}} - {{envoy_response_code}}"
    }
   ]
  },
  {
   "title": "Ingress Success Rate (non-4|5xx Responses)",
   "type": "timeseries",
   "description": "NOTE: Not including 404s in this metric, since a  404 is a normal response for errant requests",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (ingress) (\n  label_replace(\n      sum by (envoy_cluster_name) (\n        rate(\n          envoy_cluster_upstream_rq_xx{cluster=~\"$cluster\",envoy_cluster_name=~\"${namespace}_${service}_\\\\d+\",envoy_response_code_class!~\"4|5\",namespace=\"${contour_namespace}\"}[5m]\n        )\n      )\n    /\n      (\n        sum by (envoy_cluster_name) (\n          rate(\n            envoy_cluster_upstream_rq_xx{cluster=~\"$cluster\",envoy_cluster_name=~\"${namespace}_${service}_\\\\d+\",envoy_response_code!~\"404\",namespace=\"${contour_namespace}\"}[5m]\n          )\n        )\n      ),\n    \"ingress\",\n    \"$1/$2\",\n    \"envoy_cluster_name\",\n    \"^([a-z\\\\-]+)_([a-z\\\\-]+)_\\\\d+$\"\n  )\n)",
     "legendFormat": "{{ingress}}"
    }
   ]
  },
  {
   "title": "Service Total",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum by (ingress) (\n  label_replace(\n    rate(\n      envoy_cluster_upstream_cx_total{cluster=~\"$cluster\",envoy_cluster_name=~\"${namespace}_${service}_\\\\d+\",namespace=\"${contour_namespace}\"}[1m]\n    ),\n    \"ingress\",\n    \"$1/$2\",\n    \"envoy_cluster_name\",\n    \"^([a-z\\\\-]+)_([a-z\\\\-]+)_\\\\d+$\"\n  )\n)"
    },
    {
     "expr": "sum by (ingress) (\n  label_replace(\n    rate(\n      envoy_cluster_upstream_rq_total{cluster=~\"$cluster\",envoy_cluster_name=~\"${namespace}_${service}_\\\\d+\",namespace=\"${contour_namespace}\"}[1m]\n    ),\n    \"ingress\",\n    \"$1/$2\",\n    \"envoy_cluster_name\",\n    \"^([a-z\\\\-]+)_([a-z\\\\-]+)_\\\\d+$\"\n  )\n)"
    },
    {
     "expr": "histogram_quantile(\n  0.5,\n  sum by (le, ingress_namespace, ingress) (\n    label_replace(\n      rate(\n        envoy_cluster_upstream_rq_time_bucket{cluster=~\"$cluster\",envoy_cluster_name=~\"${namespace}_${service}_\\\\d+\",namespace=\"${contour_namespace}\"}[1m]\n      ),\n      \"ingress\",\n      \"$1/$2\",\n      \"envoy_cluster_name\",\n      \"^([a-z\\\\-]+)_([a-z\\\\-]+)_\\\\d+$\"\n    )\n  )\n)"
    },
    {
     "expr": "histogram_quantile(\n  0.9,\n  sum by (le, ingress) (\n    label_replace(\n      rate(\n        envoy_cluster_upstream_rq_time_bucket{cluster=~\"$cluster\",envoy_cluster_name=~\"${namespace}_${service}_\\\\d+\",namespace=\"${contour_namespace}\"}[1m]\n      ),\n      \"ingress\",\n      \"$1/$2\",\n      \"envoy_cluster_name\",\n      \"^([a-z\\\\-]+)_([a-z\\\\-]+)_\\\\d+$\"\n    )\n  )\n)"
    },
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le, ingress) (\n    label_replace(\n      rate(\n        envoy_cluster_upstream_rq_time_bucket{cluster=~\"$cluster\",envoy_cluster_name=~\"${namespace}_${service}_\\\\d+\",namespace=\"${contour_namespace}\"}[1m]\n      ),\n      \"ingress\",\n      \"$1/$2\",\n      \"envoy_cluster_name\",\n      \"^([a-z\\\\-]+)_([a-z\\\\-]+)_\\\\d+$\"\n    )\n  )\n)"
    },
    {
     "expr": "sum by (ingress) (\n  label_replace(\n    irate(\n      envoy_cluster_upstream_cx_rx_bytes_total{cluster=~\"$cluster\",envoy_cluster_name=~\"${namespace}_${service}_\\\\d+\",namespace=\"${contour_namespace}\"}[1m]\n    ),\n    \"ingress\",\n    \"$1/$2\",\n    \"envoy_cluster_name\",\n    \"^([a-z\\\\-]+)_([a-z\\\\-]+)_\\\\d+$\"\n  )\n)"
    },
    {
     "expr": "sum by (ingress) (\n  label_replace(\n    irate(\n      envoy_cluster_upstream_cx_tx_bytes_total{cluster=~\"$cluster\",envoy_cluster_name=~\"${namespace}_${service}_\\\\d+\",namespace=\"${contour_namespace}\"}[1m]\n    ),\n    \"ingress\",\n    \"$1/$2\",\n    \"envoy_cluster_name\",\n    \"^([a-z\\\\-]+)_([a-z\\\\-]+)_\\\\d+$\"\n  )\n)"
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Upstream Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (ingress) (\n  label_replace(\n    irate(\n      envoy_cluster_upstream_cx_rx_bytes_total{cluster=~\"$cluster\",envoy_cluster_name=~\"${namespace}_${service}_\\\\d+\",namespace=\"${contour_namespace}\"}[1m]\n    ),\n    \"ingress\",\n    \"$1/$2\",\n    \"envoy_cluster_name\",\n    \"^([a-z\\\\-]+)_([a-z\\\\-]+)_\\\\d+$\"\n  )\n)",
     "legendFormat": "{{ ingress }} - In"
    },
    {
     "expr": "-sum by (ingress) (\n  label_replace(\n    irate(\n      envoy_cluster_upstream_cx_tx_bytes_total{cluster=~\"$cluster\",envoy_cluster_name=~\"${namespace}_${service}_\\\\d+\",namespace=\"${contour_namespace}\"}[1m]\n    ),\n    \"ingress\",\n    \"$1/$2\",\n    \"envoy_cluster_name\",\n    \"^([a-z\\\\-]+)_([a-z\\\\-]+)_\\\\d+$\"\n  )\n)",
     "legendFormat": "{{ ingress }} - Out"
    },
    {
     "expr": "sum(\n  irate(\n    envoy_cluster_upstream_cx_rx_bytes_total{cluster=~\"$cluster\",envoy_cluster_name=~\"${namespace}_${service}_\\\\d+\",namespace=\"${contour_namespace}\"}[1m]\n  )\n)",
     "legendFormat": "Total - In"
    },
    {
     "expr": "-sum(\n  irate(\n    envoy_cluster_upstream_cx_tx_bytes_total{cluster=~\"$cluster\",envoy_cluster_name=~\"${namespace}_${service}_\\\\d+\",namespace=\"${contour_namespace}\"}[1m]\n  )\n)",
     "legendFormat": "Total - Out"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Total active requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (ingress) (\n  label_replace(\n    envoy_cluster_upstream_rq_active{cluster=~\"$cluster\",envoy_cluster_name=~\"${namespace}_${service}_\\\\d+\",namespace=\"${contour_namespace}\"},\n    \"ingress\",\n    \"$1/$2\",\n    \"envoy_cluster_name\",\n    \"^([a-z\\\\-]+)_([a-z\\\\-]+)_\\\\d+$\"\n  )\n)",
     "legendFormat": "{{ingress}}"
    }
   ]
  },
  {
   "title": "Ingress Request Volume",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 14, "x": 10, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (ingress) (\n  label_replace(\n    rate(\n      envoy_cluster_upstream_rq_total{cluster=~\"$cluster\",envoy_cluster_name=~\"${namespace}_${service}_\\\\d+\",namespace=\"${contour_namespace}\"}[1m]\n    ),\n    \"ingress\",\n    \"$1/$2\",\n    \"envoy_cluster_name\",\n    \"^([a-z\\\\-]+)_([a-z\\\\-]+)_\\\\d+$\"\n  )\n)",
     "legendFormat": "{{ingress}}"
    }
   ]
  },
  {
   "title": "New Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (ingress) (\n  label_replace(\n    increase(\n      envoy_cluster_upstream_rq_total{cluster=~\"$cluster\",envoy_cluster_name=~\"${namespace}_${service}_\\\\d+\",namespace=\"${contour_namespace}\"}[2m]\n    ),\n    \"ingress\",\n    \"$1/$2\",\n    \"envoy_cluster_name\",\n    \"^([a-z\\\\-]+)_([a-z\\\\-]+)_\\\\d+$\"\n  )\n)",
     "legendFormat": "{{ingress}}"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Total active connections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (ingress) (\n  label_replace(\n    envoy_cluster_upstream_cx_active{cluster=~\"$cluster\",envoy_cluster_name=~\"${namespace}_${service}_\\\\d+\",namespace=\"${contour_namespace}\"},\n    \"ingress\",\n    \"$1/$2\",\n    \"envoy_cluster_name\",\n    \"^([a-z\\\\-]+)_([a-z\\\\-]+)_\\\\d+$\"\n  )\n)",
     "legendFormat": "{{ingress}}"
    }
   ]
  },
  {
   "title": "Ingress Connection Volume",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 14, "x": 10, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (ingress) (\n  label_replace(\n    rate(\n      envoy_cluster_upstream_cx_total{cluster=~\"$cluster\",envoy_cluster_name=~\"${namespace}_${service}_\\\\d+\",namespace=\"${contour_namespace}\"}[1m]\n    ),\n    \"ingress\",\n    \"$1/$2\",\n    \"envoy_cluster_name\",\n    \"^([a-z\\\\-]+)_([a-z\\\\-]+)_\\\\d+$\"\n  )\n)",
     "legendFormat": "{{ingress}}"
    }
   ]
  },
  {
   "title": "New Connections ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (ingress) (\n  label_replace(\n    increase(\n      envoy_cluster_upstream_cx_total{cluster=~\"$cluster\",envoy_cluster_name=~\"${namespace}_${service}_\\\\d+\",namespace=\"${contour_namespace}\"}[2m]\n    ),\n    \"ingress\",\n    \"$1/$2\",\n    \"envoy_cluster_name\",\n    \"^([a-z\\\\-]+)_([a-z\\\\-]+)_\\\\d+$\"\n  )\n)",
     "legendFormat": "{{ingress}}"
    }
   ]
  }
 ]
}