{
 "title": "Flux Cluster Stats",
 "tags": [ "flux" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(up, cluster)" } },
   {
    "name": "operator_namespace",
    "query": {
     "query": "label_values(gotk_reconcile_duration_seconds_sum{cluster=~\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(gotk_resource_info{cluster=~\"$cluster\"}, exported_namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster Reconcilers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(\n  gotk_resource_info{cluster=~\"$cluster\",customresource_kind=~\"Kustomization|HelmRelease\",exported_namespace=~\"$namespace\"}\n)"
    }
   ]
  },
  {
   "title": "Failing Reconcilers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(\n  gotk_resource_info{cluster=~\"$cluster\",customresource_kind=~\"Kustomization|HelmRelease\",exported_namespace=~\"$namespace\",ready=\"False\"}\n)"
    }
   ]
  },
  {
   "title": "Kubernetes Manifests Sources",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(\n  gotk_resource_info{cluster=~\"$cluster\",customresource_kind=~\"GitRepository|HelmRepository|Bucket|OCIRepository\",exported_namespace=~\"$namespace\"}\n)"
    }
   ]
  },
  {
   "title": "Failing Sources",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(\n  gotk_resource_info{cluster=~\"$cluster\",customresource_kind=~\"GitRepository|HelmRepository|Bucket|OCIRepository\",exported_namespace=~\"$namespace\",ready=\"False\"}\n)"
    }
   ]
  },
  {
   "title": "Reconciler ops avg. duration",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (kind) (\n    rate(\n      gotk_reconcile_duration_seconds_sum{cluster=~\"$cluster\",exported_namespace=~\"$namespace\",kind=~\"Kustomization|HelmRelease\",namespace=~\"$operator_namespace\"}[5m]\n    )\n  )\n/\n  sum by (kind) (\n    rate(\n      gotk_reconcile_duration_seconds_count{cluster=~\"$cluster\",exported_namespace=~\"$namespace\",kind=~\"Kustomization|HelmRelease\",namespace=~\"$operator_namespace\"}[5m]\n    )\n  )",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Source ops avg. duration",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (kind) (\n    rate(\n      gotk_reconcile_duration_seconds_sum{cluster=~\"$cluster\",exported_namespace=~\"$namespace\",kind=~\"GitRepository|HelmRepository|Bucket|OCIRepository\",namespace=~\"$operator_namespace\"}[5m]\n    )\n  )\n/\n  sum by (kind) (\n    rate(\n      gotk_reconcile_duration_seconds_count{cluster=~\"$cluster\",exported_namespace=~\"$namespace\",kind=~\"GitRepository|HelmRepository|Bucket|OCIRepository\",namespace=~\"$operator_namespace\"}[5m]\n    )\n  )",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Cluster reconciliation readiness ",
   "type": "table",
   "gridPos": { "h": 22, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "gotk_resource_info{cluster=~\"$cluster\",customresource_kind=~\"Kustomization|HelmRelease\",exported_namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Source acquisition readiness ",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "gotk_resource_info{cluster=~\"$cluster\",customresource_kind=~\"GitRepository|HelmRepository|Bucket|OCIRepository\",exported_namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Suspended Objects",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "gotk_resource_info{cluster=~\"$cluster\",exported_namespace=~\"$namespace\",suspended=\"true\"}"
    }
   ]
  },
  { "title": "Timing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Cluster reconciliation duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (kind, name) (\n    rate(\n      gotk_reconcile_duration_seconds_sum{cluster=~\"$cluster\",exported_namespace=~\"$namespace\",kind=~\"Kustomization|HelmRelease\",namespace=~\"$operator_namespace\"}[5m]\n    )\n  )\n/\n  sum by (kind, name) (\n    rate(\n      gotk_reconcile_duration_seconds_count{cluster=~\"$cluster\",exported_namespace=~\"$namespace\",kind=~\"Kustomization|HelmRelease\",namespace=~\"$operator_namespace\"}[5m]\n    )\n  )",
     "legendFormat": "{{kind}}/{{name}}"
    }
   ]
  },
  {
   "title": "Source acquisition duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (kind, name) (\n    rate(\n      gotk_reconcile_duration_seconds_sum{cluster=~\"$cluster\",exported_namespace=~\"$namespace\",kind=~\"GitRepository|HelmRepository|Bucket|OCIRepository\",namespace=~\"$operator_namespace\"}[5m]\n    )\n  )\n/\n  sum by (kind, name) (\n    rate(\n      gotk_reconcile_duration_seconds_count{cluster=~\"$cluster\",exported_namespace=~\"$namespace\",kind=~\"GitRepository|HelmRepository|Bucket|OCIRepository\",namespace=~\"$operator_namespace\"}[5m]\n    )\n  )",
     "legendFormat": "{{kind}}/{{name}}"
    }
   ]
  }
 ]
}