{
 "title": "Grafana Overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(up, cluster)" } },
   {
    "name": "job",
    "query": {
     "query": "label_values(grafana_build_info{cluster=~\"$cluster\"}, job)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(grafana_build_info{cluster=~\"$cluster\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Firing Alerts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "grafana_alerting_result_total{cluster=~\"$cluster\",instance=~\"$instance\",job=~\"$job\",state=\"alerting\"}"
    }
   ]
  },
  {
   "title": "Dashboards",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(grafana_stat_totals_dashboard{cluster=~\"$cluster\",instance=~\"$instance\",job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Build Info",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "grafana_build_info{cluster=~\"$cluster\",instance=~\"$instance\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (status_code) (\n  irate(\n    grafana_http_request_duration_seconds_count{cluster=~\"$cluster\",instance=~\"$instance\",job=~\"$job\"}[1m]\n  )\n)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n    0.99,\n    sum by (le) (\n      irate(\n        grafana_http_request_duration_seconds_bucket{cluster=~\"$cluster\",instance=~\"$instance\",job=~\"$job\"}[$__rate_interval]\n      )\n    )\n  )\n*\n  1",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(\n    0.5,\n    sum by (le) (\n      irate(\n        grafana_http_request_duration_seconds_bucket{cluster=~\"$cluster\",instance=~\"$instance\",job=~\"$job\"}[$__rate_interval]\n      )\n    )\n  )\n*\n  1",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "sum(\n      irate(\n        grafana_http_request_duration_seconds_sum{cluster=~\"$cluster\",instance=~\"$instance\",job=~\"$job\"}[$__rate_interval]\n      )\n    )\n  *\n    1\n/\n  sum(\n    irate(\n      grafana_http_request_duration_seconds_count{cluster=~\"$cluster\",instance=~\"$instance\",job=~\"$job\"}[$__rate_interval]\n    )\n  )",
     "legendFormat": "Average"
    }
   ]
  }
 ]
}