apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kamaji-console
spec:
  refreshInterval: '1h'
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: kamaji-console-secrets
    template:
      engineVersion: v2
      data:
        ADMIN_EMAIL: '{{ .email }}'
        ADMIN_PASSWORD: '{{ .password }}'
        JWT_SECRET: '{{ .jwtsecret }}'
        NEXTAUTH_URL: 'https://kamaji.bealv-mgmt.lan'
  data:
    - secretKey: email
      remoteRef:
        key: secrets/kamaji-console/config
        property: username
    - secretKey: password
      remoteRef:
        key: secrets/kamaji-console/config
        property: password
    - secretKey: jwtsecret
      remoteRef:
        key: secrets/kamaji-console/config
        property: jwtsecret
