apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: proxmox-csi
  namespace: proxmox-csi
spec:
  interval: 5m0s
  chart:
    spec:
      chart: proxmox-csi-plugin
      version: 0.3.5
      sourceRef:
        kind: HelmRepository
        name: proxmox-csi
        namespace: proxmox-csi
  values:
    existingConfigSecret: proxmox-csi-secrets
    existingConfigSecretKey: config.yaml
