apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: disk
  annotations:
    storageclass.kubernetes.io/is-default-class: true
parameters:
  csi.storage.k8s.io/fstype: ext4
  ## Proxmox storage ID
  storage: disk
  ssd: 'true'
mountOptions:
  # Common for ssd
  - noatime
allowedTopologies:
  - matchLabelExpressions:
      - key: topology.kubernetes.io/region
        values:
          - proxmox-alv
      - key: topology.kubernetes.io/zone
        values:
          - proxmox-alv
provisioner: csi.proxmox.sinextra.dev
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: disk-hdd
parameters:
  csi.storage.k8s.io/fstype: ext4
  ## Proxmox storage ID
  storage: disk_hdd
  ssd: 'false'
allowedTopologies:
  - matchLabelExpressions:
      - key: topology.kubernetes.io/region
        values:
          - proxmox-alv
      - key: topology.kubernetes.io/zone
        values:
          - proxmox-alv
provisioner: csi.proxmox.sinextra.dev
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
