apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-credentials
spec:
  refreshInterval: '1h'
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: minio-credentials
    template:
      engineVersion: v2
      data:
        cloud: |
          [default]
          aws_access_key_id = {{ .aws_access_key_id }}
          aws_secret_access_key = {{ .aws_secret_access_key }}
        AWS_ACCESS_KEY_ID: '{{ .aws_access_key_id }}'
        AWS_SECRET_ACCESS_KEY: '{{ .aws_secret_access_key }}'
  data:
    - secretKey: aws_access_key_id
      remoteRef:
        key: secrets/minio/mgmt
        property: MINIO_ROOT_USER
    - secretKey: aws_secret_access_key
      remoteRef:
        key: secrets/minio/mgmt
        property: MINIO_ROOT_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-credentials-clusters
spec:
  refreshInterval: '1h'
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: minio-credentials-clusters
    template:
      engineVersion: v2
      data:
        cloud: |
          [default]
          aws_access_key_id = {{ .aws_access_key_id }}
          aws_secret_access_key = {{ .aws_secret_access_key }}
        AWS_ACCESS_KEY_ID: '{{ .aws_access_key_id }}'
        AWS_SECRET_ACCESS_KEY: '{{ .aws_secret_access_key }}'
  data:
    - secretKey: aws_access_key_id
      remoteRef:
        key: secrets/minio/clusters
        property: MINIO_ROOT_USER
    - secretKey: aws_secret_access_key
      remoteRef:
        key: secrets/minio/clusters
        property: MINIO_ROOT_PASSWORD
---
