apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-mgmt
spec:
  selector:
    matchLabels:
      app: minio-mgmt
  template:
    metadata:
      labels:
        app: minio-mgmt
    spec:
      containers:
        - name: minio
          image: minio/minio:latest
          args:
            - server
            - /storage
            - --console-address
            - ':9001'
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: minio
                  key: MINIO_ROOT_USER
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio
                  key: MINIO_ROOT_PASSWORD
          ports:
            - name: api
              containerPort: 9000
            - name: console
              containerPort: 9001
          volumeMounts:
            - name: storage
              mountPath: '/storage'
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: minio-mgmt
