apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: proxmox-csi-secrets
spec:
  refreshInterval: '1h'
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: proxmox-csi-secrets
    template:
      engineVersion: v2
      data:
        config.yaml: |
          features:
            provider: capmox
          clusters:
            # List of Proxmox clusters, region mast be unique
            - url: https://proxmox.bealv.lan:8006/api2/json
              insecure: true
              token_id: "{{ .tokenid }}"
              token_secret: "{{ .secret }}"
              region: proxmox-alv
  data:
    - secretKey: tokenid
      remoteRef:
        key: secrets/proxmox/CSI
        property: tokenid
    - secretKey: secret
      remoteRef:
        key: secrets/proxmox/CSI
        property: secret
