resources:
  - alertmanager-config.yaml
  - secrets.yaml
transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: notImportantHere
      namespace: monitoring
    unsetOnly: true
    setRoleBindingSubjects: none
