apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana
spec:
  refreshInterval: '1h'
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: grafana-secrets
  data:
    - secretKey: discordwebhookurl
      remoteRef:
        key: secrets/grafana/config
        property: discordwebhookurl
---
