apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: cilium
      version: '1.17.0'
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: kube-system
      interval: 1h
  values:
    k8sServiceHost: 10.250.0.9
    k8sServicePort: 6443
    operator:
      replicas: 1
      updateStrategy:
        type: Recreate
        rollingUpdate: null
    l2announcements:
      enabled: true
    socketLB:
      hostNamespaceOnly: true
    kubeProxyReplacement: true
    envoy:
      enabled: false
    cni:
      exclusive: false
    ipam:
      operator:
        clusterPoolIPv4PodCIDRList:
          - 10.244.0.0/16
        clusterPoolIPv4MaskSize: 23
