apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kamaji
spec:
  interval: 1h
  url: https://github.com/clastix/kamaji.git
  ref:
    tag: 26.9.5-edge
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts/
