apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kamaji
spec:
  interval: 1m
  url: https://github.com/clastix/kamaji.git
  ref:
    tag: edge-25.8.2
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts/
