apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kamaji
spec:
  interval: 1h0m0s
  chart:
    spec:
      chart: charts/kamaji
      version: '*'
      sourceRef:
        kind: GitRepository
        name: kamaji
        namespace: kamaji-system
  values:
    replicaCount: 1
    image:
      repository: clastix/kamaji
      pullPolicy: Always
      tag: edge-24.12.1
    kamaji-etcd:
      deploy: true
      fullnameOverride: kamaji-etcd
      clusterDomain: bealv-mgmt.local
      datastore:
        enabled: true
        name: default
