apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: crossplane
  namespace: crossplane-system
spec:
  interval: 1h0m0s
  chart:
    spec:
      chart: crossplane
      version: 1.19.0
      sourceRef:
        kind: HelmRepository
        name: crossplane
        namespace: crossplane-system
  values:
    replicas: 1
    deploymentStrategy: RollingUpdate
    image:
      repository: xpkg.upbound.io/crossplane/crossplane
      tag: ''
