- op: add
  path: /spec/ingress/-
  value:
    from:
      - podSelector:
          matchLabels:
            app: grafana
    ports:
      - protocol: TCP
        port: 9093
- op: add
  path: /spec/ingress/-
  value:
    from:
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: grafana-operator
    ports:
      - protocol: TCP
        port: 9093

