apiVersion: v1
kind: Namespace
metadata:
  name: capi-ipam-in-cluster-system
---
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: IPAMProvider
metadata:
  name: ipamincluster
  namespace: capi-ipam-in-cluster-system
spec:
  version: v1.0.0
  fetchConfig:
    url: https://github.com/kubernetes-sigs/cluster-api-ipam-provider-in-cluster/releases/download/v1.0.0/ipam-components.yaml
