apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bealv-proxmox
  namespace: capmox-system
spec:
  refreshInterval: '1h'
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: bealv-proxmox
  data:
    - secretKey: PROXMOX_TOKEN
      remoteRef:
        key: secrets/proxmox/capmox
        property: tokenid
    - secretKey: PROXMOX_SECRET
      remoteRef:
        key: secrets/proxmox/capmox
        property: secret
    - secretKey: PROXMOX_URL
      remoteRef:
        key: secrets/proxmox/capmox
        property: url
---
## duplicate because on restart of the controller, it takes another secret
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: capmox-manager-credentials
  namespace: capmox-system
spec:
  refreshInterval: '1h'
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: capmox-manager-credentials
  data:
    - secretKey: token
      remoteRef:
        key: secrets/proxmox/capmox
        property: tokenid
    - secretKey: secret
      remoteRef:
        key: secrets/proxmox/capmox
        property: secret
    - secretKey: url
      remoteRef:
        key: secrets/proxmox/capmox
        property: url
