apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trust-manager
spec:
  interval: 5m
  chart:
    spec:
      chart: trust-manager
      version: v0.17.1
      sourceRef:
        kind: HelmRepository
        name: trust-manager
      interval: 1h
  values:
    replicaCount: 1
    secretTargets:
      authorizedSecretsAll: true
      enabled: true
