apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns-internal
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns-internal
  template:
    metadata:
      labels:
        app: external-dns-internal
    spec:
      serviceAccountName: external-dns
      containers:
        - name: external-dns
          image: registry.k8s.io/external-dns/external-dns:v0.15.1
          args:
            - --source=ingress
            - --source=service
            - --source=contour-httpproxy
            - --provider=pdns
            - --domain-filter=bealv-mgmt.lan
            - --log-level=debug
            - --interval=30s
            - --txt-owner-id=bealv-mgmt
          env:
            - name: EXTERNAL_DNS_PDNS_SERVER
              value: 'http://powerdns-api.powerdns.svc'
            - name: EXTERNAL_DNS_PDNS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: external-dns-internal
                  key: api_key
---
