apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio
  namespace: minio
spec:
  refreshInterval: '1h'
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: minio
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: secrets/minio/mgmt
        property: MINIO_ROOT_USER
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: secrets/minio/mgmt
        property: MINIO_ROOT_PASSWORD
    - secretKey: MINIO_ROOT_USER
      remoteRef:
        key: secrets/minio/mgmt
        property: MINIO_ROOT_USER
    - secretKey: MINIO_ROOT_PASSWORD
      remoteRef:
        key: secrets/minio/mgmt
        property: MINIO_ROOT_PASSWORD
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-clusters
  namespace: minio-clusters
spec:
  refreshInterval: '1h'
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: minio-clusters
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: secrets/minio/clusters
        property: MINIO_ROOT_USER
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: secrets/minio/clusters
        property: MINIO_ROOT_PASSWORD
    - secretKey: MINIO_ROOT_USER
      remoteRef:
        key: secrets/minio/clusters
        property: MINIO_ROOT_USER
    - secretKey: MINIO_ROOT_PASSWORD
      remoteRef:
        key: secrets/minio/clusters
        property: MINIO_ROOT_PASSWORD
