apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: chihiro
spec:
  refreshInterval: '1h'
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: chihiro-secrets
    template:
      engineVersion: v2
      data:
        session_key: '{{ .session_key }}'
        client_secret: '{{ .client_secret }}'
  data:
    - secretKey: session_key
      remoteRef:
        key: secrets/chihiro/config
        property: session_key
    - secretKey: client_secret
      remoteRef:
        key: secrets/chihiro/config
        property: client_secret
