name: Updatecli
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *' # every 6 hours
permissions:
  contents: 'write'
  pull-requests: 'write'
jobs:
  updatecli:
    runs-on: 'bealv-runners'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set environment variables
        run: |
          echo "APP_ID=$APP_ID" >> $GITHUB_ENV
          echo "APP_PRIVATE_KEY=$APP_PRIVATE_KEY" | awk '{printf "%s\\n", $0}' >> $GITHUB_ENV
          NIXPKGS_URL=$(jq -r .pins.nixpkgs.url npins/sources.json)
          echo "NIX_PATH='nixpkgs=$NIXPKGS_URL'" >> $GITHUB_ENV
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ env.APP_ID }}
          private-key: ${{ env.APP_PRIVATE_KEY }}
      - name: Install Updatecli in the runner
        uses: updatecli/updatecli-action@v2
        with:
          version: v0.82.0
      - name: Run Updatecli in apply mode
        run: 'updatecli apply --config ./updatecli/updatecli.d --values updatecli/values.yaml'
        env:
          UPDATECLI_GITHUB_TOKEN: '${{ steps.app-token.outputs.token }}'
          UPDATECLI_GITHUB_TOKEN_USER: '${{ steps.app-token.outputs.app-slug }}'
