name: Updatecli
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *' # every 6 hours
permissions:
  contents: 'write'
  pull-requests: 'write'
jobs:
  updatecli:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Free Disk Space
        uses: endersonmenezes/free-disk-space@v2
        with:
          remove_android: true
          remove_dotnet: true
          remove_haskell: true
          remove_tool_cache: true
          remove_swap: true
          remove_packages: 'azure-cli google-cloud-cli microsoft-edge-stable google-chrome-stable firefox postgresql* temurin-* *llvm* mysql* dotnet-sdk-*'
          remove_packages_one_command: true
          remove_folders: '/usr/share/swift /usr/share/miniconda /usr/share/az* /usr/local/lib/node_modules /usr/local/share/chromium /usr/local/share/powershell /usr/local/julia /usr/local/aws-cli /usr/local/aws-sam-cli /usr/share/gradle'
          testing: false
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Updatecli in the runner
        uses: updatecli/updatecli-action@v2
      - name: Get Nixpkgs revision for nixfmt
        run: |
          # This should not be a URL, because it would allow PRs to run arbitrary code in CI!
          url=$(jq -r .pins.nixpkgs.url npins/sources.json)
          echo "url=$url" >> "$GITHUB_ENV"
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.UPCLI_APP_ID }}
          private-key: ${{ secrets.UPCLI_SECRET_ID }}
      - uses: cachix/install-nix-action@ba0dd844c9180cbf77aa72a116d6fbc515d0e87b # v27
        with:
          nix_path: nixpkgs=${{ env.url }}
          extra_nix_config: |
            fallback = true
            trusted-public-keys = didactiklabs-nixcache:PxLKN0+ZkP07M8g8/B6xbP6A4MYpqQg6LH7V3muiy/0= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://s3.didactiklabs.io/nix-cache https://cache.nixos.org/
      - name: Run Updatecli in apply mode
        run: 'updatecli apply --config ./updatecli/updatecli.d --values updatecli/values.yaml'
        env:
          UPDATECLI_GITHUB_TOKEN: '${{ steps.app-token.outputs.token }}'
          UPDATECLI_GITHUB_TOKEN_USER: '${{ steps.app-token.outputs.app-slug }}'
